// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub phrase_setted: bool,
    #[prost(message, optional, tag = "4")]
    pub joined: ::core::option::Option<::prost_types::Timestamp>,
}
// @@protoc_insertion_point(module)
