// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Preferences {
    #[prost(enumeration = "Theme", tag = "1")]
    pub theme: i32,
    #[prost(enumeration = "Language", tag = "2")]
    pub lang: i32,
    #[prost(enumeration = "Crypt", tag = "3")]
    pub crypto: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserSelf {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub joined: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, optional, tag = "4")]
    pub phrase: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub preferences: ::core::option::Option<Preferences>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserPublic {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(enumeration = "Language", tag = "3")]
    pub lang: i32,
    #[prost(enumeration = "Crypt", tag = "4")]
    pub crypt: i32,
    #[prost(bool, tag = "5")]
    pub phrase_set: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserResponse {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<UserSelf>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<UserPublic>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeThemeRequest {
    #[prost(enumeration = "Theme", tag = "1")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeLanguageRequest {
    #[prost(enumeration = "Language", tag = "1")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeCryptRequest {
    #[prost(enumeration = "Crypt", tag = "1")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeThemeResponse {
    #[prost(enumeration = "Theme", tag = "1")]
    pub result: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeLanguageResponse {
    #[prost(enumeration = "Language", tag = "1")]
    pub result: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeCryptResponse {
    #[prost(enumeration = "Crypt", tag = "1")]
    pub result: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueChangeResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<::prost_types::Any>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Theme {
    Unspecified = 0,
    White = 1,
    Black = 2,
}
impl Theme {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "THEME_UNSPECIFIED",
            Self::White => "THEME_WHITE",
            Self::Black => "THEME_BLACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "THEME_UNSPECIFIED" => Some(Self::Unspecified),
            "THEME_WHITE" => Some(Self::White),
            "THEME_BLACK" => Some(Self::Black),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Language {
    Unspecified = 0,
    Ru = 1,
    En = 2,
}
impl Language {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LANGUAGE_UNSPECIFIED",
            Self::Ru => "LANGUAGE_RU",
            Self::En => "LANGUAGE_EN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LANGUAGE_UNSPECIFIED" => Some(Self::Unspecified),
            "LANGUAGE_RU" => Some(Self::Ru),
            "LANGUAGE_EN" => Some(Self::En),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Crypt {
    Unspecified = 0,
    Argon2id = 1,
    Sha256 = 2,
}
impl Crypt {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CRYPT_UNSPECIFIED",
            Self::Argon2id => "CRYPT_ARGON2ID",
            Self::Sha256 => "CRYPT_SHA256",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CRYPT_UNSPECIFIED" => Some(Self::Unspecified),
            "CRYPT_ARGON2ID" => Some(Self::Argon2id),
            "CRYPT_SHA256" => Some(Self::Sha256),
            _ => None,
        }
    }
}
include!("xyz.secureguard.v1.users.v1.tonic.rs");
// @@protoc_insertion_point(module)