// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub runtime_version: ::prost::alloc::string::String,
    #[prost(float, repeated, tag = "4")]
    pub supporing_ver: ::prost::alloc::vec::Vec<f32>,
    #[prost(string, tag = "5")]
    pub commit_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub reporitory: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub build_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfoResponse {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<ServerInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CompatibilityRequest {
    #[prost(float, tag = "1")]
    pub client_api_version: f32,
    #[prost(enumeration = "ClientType", tag = "2")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompatibilityResponse {
    #[prost(bool, tag = "1")]
    pub value: bool,
    #[prost(string, repeated, tag = "2")]
    pub reasons: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalisationResponse {
    #[prost(map = "string, string", tag = "1")]
    pub ru: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "2")]
    pub en: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ClientType {
    SecureguardUnspecified = 0,
    SecureguardWindows = 1,
    SecureguardMac = 2,
    SecureguardLinux = 3,
    SecureguardAndroid = 4,
    SecureguardIos = 5,
}
impl ClientType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SecureguardUnspecified => "CLIENT_TYPE_SECUREGUARD_UNSPECIFIED",
            Self::SecureguardWindows => "CLIENT_TYPE_SECUREGUARD_WINDOWS",
            Self::SecureguardMac => "CLIENT_TYPE_SECUREGUARD_MAC",
            Self::SecureguardLinux => "CLIENT_TYPE_SECUREGUARD_LINUX",
            Self::SecureguardAndroid => "CLIENT_TYPE_SECUREGUARD_ANDROID",
            Self::SecureguardIos => "CLIENT_TYPE_SECUREGUARD_IOS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CLIENT_TYPE_SECUREGUARD_UNSPECIFIED" => Some(Self::SecureguardUnspecified),
            "CLIENT_TYPE_SECUREGUARD_WINDOWS" => Some(Self::SecureguardWindows),
            "CLIENT_TYPE_SECUREGUARD_MAC" => Some(Self::SecureguardMac),
            "CLIENT_TYPE_SECUREGUARD_LINUX" => Some(Self::SecureguardLinux),
            "CLIENT_TYPE_SECUREGUARD_ANDROID" => Some(Self::SecureguardAndroid),
            "CLIENT_TYPE_SECUREGUARD_IOS" => Some(Self::SecureguardIos),
            _ => None,
        }
    }
}
include!("xyz.secureguard.api.v1.meta.v1.tonic.rs");
// @@protoc_insertion_point(module)
