// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/meta/v1/domain.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_CLIENT_TYPE_SECUREGUARD_UNSPECIFIED ClientType = 0
	ClientType_CLIENT_TYPE_SECUREGUARD_WINDOWS     ClientType = 1
	ClientType_CLIENT_TYPE_SECUREGUARD_MAC         ClientType = 2
	ClientType_CLIENT_TYPE_SECUREGUARD_LINUX       ClientType = 3
	ClientType_CLIENT_TYPE_SECUREGUARD_ANDROID     ClientType = 4
	ClientType_CLIENT_TYPE_SECUREGUARD_IOS         ClientType = 5
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLIENT_TYPE_SECUREGUARD_UNSPECIFIED",
		1: "CLIENT_TYPE_SECUREGUARD_WINDOWS",
		2: "CLIENT_TYPE_SECUREGUARD_MAC",
		3: "CLIENT_TYPE_SECUREGUARD_LINUX",
		4: "CLIENT_TYPE_SECUREGUARD_ANDROID",
		5: "CLIENT_TYPE_SECUREGUARD_IOS",
	}
	ClientType_value = map[string]int32{
		"CLIENT_TYPE_SECUREGUARD_UNSPECIFIED": 0,
		"CLIENT_TYPE_SECUREGUARD_WINDOWS":     1,
		"CLIENT_TYPE_SECUREGUARD_MAC":         2,
		"CLIENT_TYPE_SECUREGUARD_LINUX":       3,
		"CLIENT_TYPE_SECUREGUARD_ANDROID":     4,
		"CLIENT_TYPE_SECUREGUARD_IOS":         5,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_xyz_secureguard_v1_meta_v1_domain_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP(), []int{0}
}

type ServerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	SupporingVer   []float32              `protobuf:"fixed32,4,rep,packed,name=supporing_ver,json=supporingVer,proto3" json:"supporing_ver,omitempty"`
	CommitHash     string                 `protobuf:"bytes,5,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Reporitory     string                 `protobuf:"bytes,6,opt,name=reporitory,proto3" json:"reporitory,omitempty"`
	BuildTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *ServerInfo) GetSupporingVer() []float32 {
	if x != nil {
		return x.SupporingVer
	}
	return nil
}

func (x *ServerInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ServerInfo) GetReporitory() string {
	if x != nil {
		return x.Reporitory
	}
	return ""
}

func (x *ServerInfo) GetBuildTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BuildTime
	}
	return nil
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ServerInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfoResponse) GetInfo() *ServerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CompatibilityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientApiVersion float32                `protobuf:"fixed32,1,opt,name=client_api_version,json=clientApiVersion,proto3" json:"client_api_version,omitempty"`
	Type             ClientType             `protobuf:"varint,2,opt,name=type,proto3,enum=xyz.secureguard.api.v1.meta.v1.ClientType" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompatibilityRequest) Reset() {
	*x = CompatibilityRequest{}
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityRequest) ProtoMessage() {}

func (x *CompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityRequest.ProtoReflect.Descriptor instead.
func (*CompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *CompatibilityRequest) GetClientApiVersion() float32 {
	if x != nil {
		return x.ClientApiVersion
	}
	return 0
}

func (x *CompatibilityRequest) GetType() ClientType {
	if x != nil {
		return x.Type
	}
	return ClientType_CLIENT_TYPE_SECUREGUARD_UNSPECIFIED
}

type CompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Reasons       []string               `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompatibilityResponse) Reset() {
	*x = CompatibilityResponse{}
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityResponse) ProtoMessage() {}

func (x *CompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityResponse.ProtoReflect.Descriptor instead.
func (*CompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *CompatibilityResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *CompatibilityResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_xyz_secureguard_v1_meta_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_meta_v1_domain_proto_rawDesc = "" +
	"\n" +
	"'xyz/secureguard/v1/meta/v1/domain.proto\x12\x1exyz.secureguard.api.v1.meta.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x02\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fruntime_version\x18\x03 \x01(\tR\x0eruntimeVersion\x12#\n" +
	"\rsupporing_ver\x18\x04 \x03(\x02R\fsupporingVer\x12\x1f\n" +
	"\vcommit_hash\x18\x05 \x01(\tR\n" +
	"commitHash\x12\x1e\n" +
	"\n" +
	"reporitory\x18\x06 \x01(\tR\n" +
	"reporitory\x129\n" +
	"\n" +
	"build_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tbuildTime\"T\n" +
	"\x12ServerInfoResponse\x12>\n" +
	"\x04info\x18\x01 \x01(\v2*.xyz.secureguard.api.v1.meta.v1.ServerInfoR\x04info\"\x84\x01\n" +
	"\x14CompatibilityRequest\x12,\n" +
	"\x12client_api_version\x18\x01 \x01(\x02R\x10clientApiVersion\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.xyz.secureguard.api.v1.meta.v1.ClientTypeR\x04type\"G\n" +
	"\x15CompatibilityResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x18\n" +
	"\areasons\x18\x02 \x03(\tR\areasons*\xe4\x01\n" +
	"\n" +
	"ClientType\x12'\n" +
	"#CLIENT_TYPE_SECUREGUARD_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCLIENT_TYPE_SECUREGUARD_WINDOWS\x10\x01\x12\x1f\n" +
	"\x1bCLIENT_TYPE_SECUREGUARD_MAC\x10\x02\x12!\n" +
	"\x1dCLIENT_TYPE_SECUREGUARD_LINUX\x10\x03\x12#\n" +
	"\x1fCLIENT_TYPE_SECUREGUARD_ANDROID\x10\x04\x12\x1f\n" +
	"\x1bCLIENT_TYPE_SECUREGUARD_IOS\x10\x05B?Z=github.com/aesterial/secureguard/internal/api/v1/meta/v1;metab\x06proto3"

var (
	file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_meta_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_meta_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_meta_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_meta_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xyz_secureguard_v1_meta_v1_domain_proto_goTypes = []any{
	(ClientType)(0),               // 0: xyz.secureguard.api.v1.meta.v1.ClientType
	(*ServerInfo)(nil),            // 1: xyz.secureguard.api.v1.meta.v1.ServerInfo
	(*ServerInfoResponse)(nil),    // 2: xyz.secureguard.api.v1.meta.v1.ServerInfoResponse
	(*CompatibilityRequest)(nil),  // 3: xyz.secureguard.api.v1.meta.v1.CompatibilityRequest
	(*CompatibilityResponse)(nil), // 4: xyz.secureguard.api.v1.meta.v1.CompatibilityResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_meta_v1_domain_proto_depIdxs = []int32{
	5, // 0: xyz.secureguard.api.v1.meta.v1.ServerInfo.build_time:type_name -> google.protobuf.Timestamp
	1, // 1: xyz.secureguard.api.v1.meta.v1.ServerInfoResponse.info:type_name -> xyz.secureguard.api.v1.meta.v1.ServerInfo
	0, // 2: xyz.secureguard.api.v1.meta.v1.CompatibilityRequest.type:type_name -> xyz.secureguard.api.v1.meta.v1.ClientType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_meta_v1_domain_proto_init() }
func file_xyz_secureguard_v1_meta_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_meta_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_meta_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_meta_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_meta_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_meta_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_secureguard_v1_meta_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_secureguard_v1_meta_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_meta_v1_domain_proto = out.File
	file_xyz_secureguard_v1_meta_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_meta_v1_domain_proto_depIdxs = nil
}
