// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: xyz/secureguard/v1/meta/v1/service.proto

package meta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaService_ServerInformation_FullMethodName   = "/xyz.secureguard.api.v1.meta.v1.MetaService/ServerInformation"
	MetaService_ClientCompatibility_FullMethodName = "/xyz.secureguard.api.v1.meta.v1.MetaService/ClientCompatibility"
)

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaServiceClient interface {
	ServerInformation(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerInfoResponse, error)
	ClientCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) ServerInformation(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, MetaService_ServerInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ClientCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompatibilityResponse)
	err := c.cc.Invoke(ctx, MetaService_ClientCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
// All implementations should embed UnimplementedMetaServiceServer
// for forward compatibility.
type MetaServiceServer interface {
	ServerInformation(context.Context, *emptypb.Empty) (*ServerInfoResponse, error)
	ClientCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error)
}

// UnimplementedMetaServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaServiceServer struct{}

func (UnimplementedMetaServiceServer) ServerInformation(context.Context, *emptypb.Empty) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerInformation not implemented")
}
func (UnimplementedMetaServiceServer) ClientCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientCompatibility not implemented")
}
func (UnimplementedMetaServiceServer) testEmbeddedByValue() {}

// UnsafeMetaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServiceServer will
// result in compilation errors.
type UnsafeMetaServiceServer interface {
	mustEmbedUnimplementedMetaServiceServer()
}

func RegisterMetaServiceServer(s grpc.ServiceRegistrar, srv MetaServiceServer) {
	// If the following call panics, it indicates UnimplementedMetaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaService_ServiceDesc, srv)
}

func _MetaService_ServerInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ServerInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ServerInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ServerInformation(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ClientCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ClientCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ClientCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ClientCompatibility(ctx, req.(*CompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaService_ServiceDesc is the grpc.ServiceDesc for MetaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.secureguard.api.v1.meta.v1.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerInformation",
			Handler:    _MetaService_ServerInformation_Handler,
		},
		{
			MethodName: "ClientCompatibility",
			Handler:    _MetaService_ClientCompatibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xyz/secureguard/v1/meta/v1/service.proto",
}
