// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/meta/v1/service.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_meta_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_meta_v1_service_proto_rawDesc = "" +
	"\n" +
	"(xyz/secureguard/v1/meta/v1/service.proto\x12\x1exyz.secureguard.api.v1.meta.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a'xyz/secureguard/v1/meta/v1/domain.proto2\xd1\x02\n" +
	"\vMetaService\x12_\n" +
	"\x11ServerInformation\x12\x16.google.protobuf.Empty\x1a2.xyz.secureguard.api.v1.meta.v1.ServerInfoResponse\x12\x82\x01\n" +
	"\x13ClientCompatibility\x124.xyz.secureguard.api.v1.meta.v1.CompatibilityRequest\x1a5.xyz.secureguard.api.v1.meta.v1.CompatibilityResponse\x12\\\n" +
	"\fLocalisation\x12\x16.google.protobuf.Empty\x1a4.xyz.secureguard.api.v1.meta.v1.LocalisationResponseB?Z=github.com/aesterial/secureguard/internal/api/v1/meta/v1;metab\x06proto3"

var file_xyz_secureguard_v1_meta_v1_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),         // 0: google.protobuf.Empty
	(*CompatibilityRequest)(nil),  // 1: xyz.secureguard.api.v1.meta.v1.CompatibilityRequest
	(*ServerInfoResponse)(nil),    // 2: xyz.secureguard.api.v1.meta.v1.ServerInfoResponse
	(*CompatibilityResponse)(nil), // 3: xyz.secureguard.api.v1.meta.v1.CompatibilityResponse
	(*LocalisationResponse)(nil),  // 4: xyz.secureguard.api.v1.meta.v1.LocalisationResponse
}
var file_xyz_secureguard_v1_meta_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.api.v1.meta.v1.MetaService.ServerInformation:input_type -> google.protobuf.Empty
	1, // 1: xyz.secureguard.api.v1.meta.v1.MetaService.ClientCompatibility:input_type -> xyz.secureguard.api.v1.meta.v1.CompatibilityRequest
	0, // 2: xyz.secureguard.api.v1.meta.v1.MetaService.Localisation:input_type -> google.protobuf.Empty
	2, // 3: xyz.secureguard.api.v1.meta.v1.MetaService.ServerInformation:output_type -> xyz.secureguard.api.v1.meta.v1.ServerInfoResponse
	3, // 4: xyz.secureguard.api.v1.meta.v1.MetaService.ClientCompatibility:output_type -> xyz.secureguard.api.v1.meta.v1.CompatibilityResponse
	4, // 5: xyz.secureguard.api.v1.meta.v1.MetaService.Localisation:output_type -> xyz.secureguard.api.v1.meta.v1.LocalisationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_meta_v1_service_proto_init() }
func file_xyz_secureguard_v1_meta_v1_service_proto_init() {
	if File_xyz_secureguard_v1_meta_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_meta_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_meta_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_meta_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_meta_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_meta_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_meta_v1_service_proto = out.File
	file_xyz_secureguard_v1_meta_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_meta_v1_service_proto_depIdxs = nil
}
