// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/logs/v1/domain.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaLogEntry) Reset() {
	*x = KafkaLogEntry{}
	mi := &file_xyz_secureguard_v1_logs_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaLogEntry) ProtoMessage() {}

func (x *KafkaLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_logs_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaLogEntry.ProtoReflect.Descriptor instead.
func (*KafkaLogEntry) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *KafkaLogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *KafkaLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *KafkaLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KafkaLogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_xyz_secureguard_v1_logs_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_logs_v1_domain_proto_rawDesc = "" +
	"\n" +
	"'xyz/secureguard/v1/logs/v1/domain.proto\x12\x1axyz.secureguard.v1.logs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\rKafkaLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12M\n" +
	"\x06fields\x18\x05 \x03(\v25.xyz.secureguard.v1.logs.v1.KafkaLogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=github.com/aesterial/secureguard/internal/api/v1/logs/v1;logsb\x06proto3"

var (
	file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_logs_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_logs_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_logs_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_logs_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xyz_secureguard_v1_logs_v1_domain_proto_goTypes = []any{
	(*KafkaLogEntry)(nil),         // 0: xyz.secureguard.v1.logs.v1.KafkaLogEntry
	nil,                           // 1: xyz.secureguard.v1.logs.v1.KafkaLogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_logs_v1_domain_proto_depIdxs = []int32{
	2, // 0: xyz.secureguard.v1.logs.v1.KafkaLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: xyz.secureguard.v1.logs.v1.KafkaLogEntry.fields:type_name -> xyz.secureguard.v1.logs.v1.KafkaLogEntry.FieldsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_logs_v1_domain_proto_init() }
func file_xyz_secureguard_v1_logs_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_logs_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_logs_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_logs_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_logs_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_logs_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_logs_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_logs_v1_domain_proto = out.File
	file_xyz_secureguard_v1_logs_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_logs_v1_domain_proto_depIdxs = nil
}
