@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul 2>&1
title SecureGuard - Run
color 0B

cls

REM Always run relative to this .bat file location
cd /d "%~dp0" || (
    echo [X] Failed to access script directory.
    pause
    exit /b 1
)

REM Enter project folder
cd /d "client" 2>nul || (
    echo [X] Folder '"client" ' not found.
    echo     Run setup.bat first.
    pause
    exit /b 1
)

echo [*] Stopping previous app instances...
taskkill /F /IM SecureGuard.exe        >nul 2>&1
taskkill /F /IM secureguard.exe        >nul 2>&1
taskkill /F /IM password-manager.exe   >nul 2>&1

echo [*] Checking backend (gRPC :8080)...
set "BACKEND_PORT=8080"
set "BACKEND_RUNNING="
for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":%BACKEND_PORT% .*LISTENING"') do (
    set "BACKEND_RUNNING=1"
    goto :backend_ready
)

where go >nul 2>&1
if errorlevel 1 (
    echo [!] Go is not installed or not in PATH.
    echo [!] Backend was not started automatically.
    echo [!] Install Go and run: cd /d server\starter ^&^& go run .
    goto :backend_ready
)

if not exist "..\server\starter\go.mod" (
    echo [!] Backend folder '..\server\starter' not found.
    goto :backend_ready
)

if not exist "..\server\starter\.env" (
    echo [*] Creating backend .env with local defaults...
    if exist "..\server\starter\.env.example" (
        copy /Y "..\server\starter\.env.example" "..\server\starter\.env" >nul
    ) else (
        >"..\server\starter\.env" (
            echo # Auto-generated by run.bat
            echo POSTGRES_HOST=127.0.0.1
            echo POSTGRES_PORT=5432
            echo POSTGRES_USER=postgres
            echo POSTGRES_PASSWORD=postgres
            echo POSTGRES_NAME=secureguard
            echo POSTGRES_TLS=false
            echo BOOT_PORT=8080
            echo LOG_SERVICE=secureguard
            echo LOG_LEVEL=info
            echo KAFKA_ENABLED=false
            echo DEBUG_MODE=false
        )
    )
    echo [!] Created server\starter\.env
    echo [!] Edit DB credentials there if they differ from defaults.
)

echo [*] Checking database (PostgreSQL)...
set "DB_HOST=127.0.0.1"
set "DB_PORT=5432"
set "DB_USER=postgres"
set "DB_PASSWORD=postgres"
set "DB_NAME=secureguard"
if exist "..\server\starter\.env" (
    for /f "usebackq tokens=1,* delims==" %%A in ("..\server\starter\.env") do (
        set "K=%%~A"
        set "V=%%~B"
        if /I "!K!"=="POSTGRES_HOST" set "DB_HOST=!V!"
        if /I "!K!"=="POSTGRES_PORT" set "DB_PORT=!V!"
        if /I "!K!"=="POSTGRES_USER" set "DB_USER=!V!"
        if /I "!K!"=="POSTGRES_PASSWORD" set "DB_PASSWORD=!V!"
        if /I "!K!"=="POSTGRES_NAME" set "DB_NAME=!V!"
        if /I "!K!"=="POSTGRES_DB" set "DB_NAME=!V!"
    )
)

if /I "!DB_HOST!"=="localhost" set "DB_HOST=127.0.0.1"
set "DB_LOCAL="
if /I "!DB_HOST!"=="127.0.0.1" set "DB_LOCAL=1"
if /I "!DB_HOST!"=="0.0.0.0" set "DB_LOCAL=1"

set "DB_READY="
if not defined DB_LOCAL (
    echo [*] Using remote DB !DB_HOST!:!DB_PORT!
    set "DB_READY=1"
    goto :db_ready
)

for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":!DB_PORT! .*LISTENING"') do (
    set "DB_READY=1"
    goto :db_ready
)

where docker >nul 2>&1
if errorlevel 1 (
    echo [X] PostgreSQL is not listening on !DB_HOST!:!DB_PORT! and Docker is not installed.
    echo [X] Start PostgreSQL manually and rerun run.bat.
    goto :db_ready
)

docker info >nul 2>&1
if errorlevel 1 (
    echo [X] Docker is installed, but Docker Desktop/daemon is not running.
    echo [X] Start Docker and rerun run.bat.
    goto :db_ready
)

echo [*] Starting PostgreSQL in Docker...
set "PG_CONTAINER=secureguard-postgres"
set "PG_EXISTS="
for /f %%N in ('docker ps -a --format "{{.Names}}" ^| findstr /R /X /C:"!PG_CONTAINER!"') do (
    set "PG_EXISTS=1"
)

if defined PG_EXISTS (
    docker start "!PG_CONTAINER!" >nul 2>&1
) else (
    docker run -d --name "!PG_CONTAINER!" -e POSTGRES_USER=!DB_USER! -e POSTGRES_PASSWORD=!DB_PASSWORD! -e POSTGRES_DB=!DB_NAME! -p !DB_PORT!:5432 postgres:16-alpine >nul
)

set "DB_WAIT_OK="
for /l %%I in (1,1,30) do (
    for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":!DB_PORT! .*LISTENING"') do (
        set "DB_WAIT_OK=1"
        set "DB_READY=1"
        goto :db_wait_done
    )
    timeout /t 1 /nobreak >nul
)

:db_wait_done
if not defined DB_READY (
    echo [X] PostgreSQL did not become ready on !DB_HOST!:!DB_PORT!.
    goto :db_ready
)

if exist "..\server\migrations\scheme\sqlc.sql" (
    echo [*] Applying DB schema...
    docker exec -i "!PG_CONTAINER!" psql -U "!DB_USER!" -d "!DB_NAME!" < "..\server\migrations\scheme\sqlc.sql" >nul 2>&1
    if errorlevel 1 (
        echo [!] Could not auto-apply schema. You can apply it manually:
        echo     psql -U !DB_USER! -d !DB_NAME! -f server\migrations\scheme\sqlc.sql
    )
)

:db_ready
if not defined DB_READY (
    echo [X] Database is not ready. Backend start canceled.
    pause
    exit /b 1
)
echo [+] Database is ready.

echo [*] Starting backend in a separate window...
start "SecureGuard Backend" cmd /k "cd /d ..\server\starter && go run ."
timeout /t 2 /nobreak >nul

:backend_ready
if defined BACKEND_RUNNING (
    echo [+] Backend is already running.
)

REM Install deps only if needed
if not exist "node_modules\" (
    echo [*] Installing npm dependencies...

    REM Prefer npm ci when lockfile exists (more consistent)
    if exist "package-lock.json" (
        call npm ci
    ) else (
        call npm install
    )

    if errorlevel 1 (
        echo [X] npm install failed
        pause
        exit /b 1
    )
    echo [+] Dependencies installed
)

echo.
echo  Starting SecureGuard...
echo.
echo  [DEV]   npm run dev
echo  [BUILD] npm run build
echo.

set "MODE="
set /p MODE="Mode (dev/build): "
if not defined MODE set "MODE=dev"

cls

if /i "%MODE%"=="build" (
    echo  SecureGuard - BUILD
    echo.
    echo [*] Building release EXE...
    echo [*] First build can take several minutes.
    echo.
    call npm run build

    if errorlevel 1 (
        echo [X] Build failed
        pause
        exit /b 1
    )

    echo.
    echo [+] BUILD SUCCESS
    echo [+] EXE:       src-tauri\target\release\
    echo [+] Installer: src-tauri\target\release\bundle\nsis\
    echo.

    set "OPEN="
    set /p OPEN="Open folder? (y/n): "
    if /i "%OPEN%"=="y" (
        explorer "src-tauri\target\release"
    )
) else (
    echo  ==================================
    echo   SecureGuard - DEV
    echo  ==================================
    echo.
    echo [*] Starting dev mode...
    echo.
    call npm run dev
)

pause
