@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul 2>&1
title SecureGuard - Run
color 0B

cls

REM Always run relative to this .bat file location
cd /d "%~dp0" || (
    echo [X] Failed to access script directory.
    pause
    exit /b 1
)

set "ROOT=%CD%"
set "CLIENT_DIR=%ROOT%\client"
set "SERVER_DIR=%ROOT%\server\starter"
set "SERVER_ENV=%SERVER_DIR%\.env"
set "SERVER_ENV_EXAMPLE=%SERVER_DIR%\.env.example"
set "SCHEMA_FILE=%ROOT%\server\migrations\scheme\sqlc.sql"

if not exist "%CLIENT_DIR%\" (
    echo [X] Folder 'client' not found.
    pause
    exit /b 1
)

if not exist "%SERVER_DIR%\go.mod" (
    echo [X] Backend folder 'server\starter' not found.
    pause
    exit /b 1
)

echo [*] Stopping previous app instances...
taskkill /F /IM SecureGuard.exe      >nul 2>&1
taskkill /F /IM secureguard.exe      >nul 2>&1
taskkill /F /IM password-manager.exe >nul 2>&1

echo.
echo  Start target:
echo  [FULL]    backend + client
echo  [BACKEND] backend only
echo  [CLIENT]  client only
echo.

set "TARGET="
set /p TARGET="Target (full/backend/client): "
if not defined TARGET set "TARGET=full"

set "RUN_BACKEND=1"
set "RUN_CLIENT=1"

if /I "%TARGET%"=="backend" set "RUN_CLIENT="
if /I "%TARGET%"=="client" set "RUN_BACKEND="

if /I not "%TARGET%"=="full" if /I not "%TARGET%"=="backend" if /I not "%TARGET%"=="client" (
    echo [!] Unknown target '%TARGET%'. Using 'full'.
    set "TARGET=full"
    set "RUN_BACKEND=1"
    set "RUN_CLIENT=1"
)

if not exist "%SERVER_ENV%" (
    echo [*] Creating backend .env with local defaults...
    if exist "%SERVER_ENV_EXAMPLE%" (
        copy /Y "%SERVER_ENV_EXAMPLE%" "%SERVER_ENV%" >nul
        >>"%SERVER_ENV%" (
            echo.
            echo # Local overrides added by run.bat
            echo POSTGRES_HOST=127.0.0.1
            echo POSTGRES_PORT=5432
            echo POSTGRES_USER=postgres
            echo POSTGRES_PASSWORD=postgres
            echo POSTGRES_NAME=secureguard
            echo POSTGRES_TLS=false
            echo BOOT_PORT=8080
            echo REDIS_ADDR=127.0.0.1:6379
            echo REDIS_PASSWORD=
            echo REDIS_DB=0
            echo RATE_LIMIT_ENABLED=true
            echo KAFKA_ENABLED=false
        )
    ) else (
        >"%SERVER_ENV%" (
            echo # Auto-generated by run.bat
            echo POSTGRES_HOST=127.0.0.1
            echo POSTGRES_PORT=5432
            echo POSTGRES_USER=postgres
            echo POSTGRES_PASSWORD=postgres
            echo POSTGRES_NAME=secureguard
            echo POSTGRES_TLS=false
            echo BOOT_PORT=8080
            echo LOG_SERVICE=secureguard
            echo LOG_LEVEL=info
            echo REDIS_ADDR=127.0.0.1:6379
            echo REDIS_PASSWORD=
            echo REDIS_DB=0
            echo RATE_LIMIT_ENABLED=true
            echo KAFKA_ENABLED=false
            echo DEBUG_MODE=false
        )
    )
    echo [!] Created server\starter\.env
    echo [!] Edit DB credentials there if they differ from defaults.
)

set "BACKEND_PORT=50051"
set "DB_HOST=127.0.0.1"
set "DB_PORT=5432"
set "DB_USER=postgres"
set "DB_PASSWORD=postgres"
set "DB_NAME=secureguard"
set "REDIS_ADDR=127.0.0.1:6379"
set "REDIS_PASSWORD="
set "REDIS_DB=0"
set "RATE_LIMIT_ENABLED=false"

for /f "usebackq tokens=1,* delims==" %%A in ("%SERVER_ENV%") do (
    set "K=%%~A"
    set "V=%%~B"
    if /I "!K!"=="BOOT_PORT" set "BACKEND_PORT=!V!"
    if /I "!K!"=="POSTGRES_HOST" set "DB_HOST=!V!"
    if /I "!K!"=="POSTGRES_PORT" set "DB_PORT=!V!"
    if /I "!K!"=="POSTGRES_USER" set "DB_USER=!V!"
    if /I "!K!"=="POSTGRES_PASSWORD" set "DB_PASSWORD=!V!"
    if /I "!K!"=="POSTGRES_NAME" set "DB_NAME=!V!"
    if /I "!K!"=="POSTGRES_DB" set "DB_NAME=!V!"
    if /I "!K!"=="REDIS_ADDR" set "REDIS_ADDR=!V!"
    if /I "!K!"=="REDIS_PASSWORD" set "REDIS_PASSWORD=!V!"
    if /I "!K!"=="REDIS_DB" set "REDIS_DB=!V!"
    if /I "!K!"=="RATE_LIMIT_ENABLED" set "RATE_LIMIT_ENABLED=!V!"
)

if not defined BACKEND_PORT set "BACKEND_PORT=50051"
set "BACKEND_HOST=127.0.0.1"
set "BACKEND_ENDPOINT=http://%BACKEND_HOST%:%BACKEND_PORT%"
if not defined REDIS_ADDR set "REDIS_ADDR=127.0.0.1:6379"
set "REDIS_EFFECTIVE_ADDR=!REDIS_ADDR!"
set "REDIS_REQUIRED="
if /I "!RATE_LIMIT_ENABLED!"=="true" set "REDIS_REQUIRED=1"
if /I "!RATE_LIMIT_ENABLED!"=="1" set "REDIS_REQUIRED=1"
if /I "!REDIS_EFFECTIVE_ADDR!"=="redis:6379" set "REDIS_EFFECTIVE_ADDR=127.0.0.1:6379"
for /f "tokens=1,2 delims=:" %%A in ("!REDIS_EFFECTIVE_ADDR!") do (
    set "REDIS_HOST=%%~A"
    set "REDIS_PORT=%%~B"
)
if not defined REDIS_HOST set "REDIS_HOST=127.0.0.1"
if not defined REDIS_PORT set "REDIS_PORT=6379"
if /I "!REDIS_HOST!"=="localhost" set "REDIS_HOST=127.0.0.1"
if /I "!REDIS_HOST!"=="redis" (
    set "REDIS_HOST=127.0.0.1"
    set "REDIS_EFFECTIVE_ADDR=127.0.0.1:!REDIS_PORT!"
)
set "REDIS_LOCAL="
if /I "!REDIS_HOST!"=="127.0.0.1" set "REDIS_LOCAL=1"
if /I "!REDIS_HOST!"=="0.0.0.0" set "REDIS_LOCAL=1"

echo [*] Backend endpoint: %BACKEND_ENDPOINT%
if defined REDIS_REQUIRED (
    echo [*] Redis endpoint: !REDIS_EFFECTIVE_ADDR!
)

set "BACKEND_RUNNING="
for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":%BACKEND_PORT% .*LISTENING"') do (
    set "BACKEND_RUNNING=1"
    goto :backend_status_ready
)

:backend_status_ready
if defined BACKEND_RUNNING (
    echo [+] Backend is already listening on port %BACKEND_PORT%.
) else (
    echo [*] Backend is not running on port %BACKEND_PORT%.
)

if not defined RUN_BACKEND goto :after_backend

where go >nul 2>&1
if errorlevel 1 (
    echo [!] Go is not installed or not in PATH.
    echo [!] Backend was not started automatically.
    echo [!] Install Go and run: cd /d server\starter ^&^& go run .
    goto :after_backend
)

if defined BACKEND_RUNNING goto :after_backend

echo [*] Checking database (PostgreSQL)...
if /I "!DB_HOST!"=="localhost" set "DB_HOST=127.0.0.1"
set "DB_LOCAL="
if /I "!DB_HOST!"=="127.0.0.1" set "DB_LOCAL=1"
if /I "!DB_HOST!"=="0.0.0.0" set "DB_LOCAL=1"

set "DB_READY="
if not defined DB_LOCAL (
    echo [*] Using remote DB !DB_HOST!:!DB_PORT!
    set "DB_READY=1"
    goto :db_ready
)

for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":!DB_PORT! .*LISTENING"') do (
    set "DB_READY=1"
    goto :db_ready
)

where docker >nul 2>&1
if errorlevel 1 (
    echo [X] PostgreSQL is not listening on !DB_HOST!:!DB_PORT! and Docker is not installed.
    echo [X] Start PostgreSQL manually and rerun run.bat.
    goto :db_ready
)

docker info >nul 2>&1
if errorlevel 1 (
    echo [X] Docker is installed, but Docker Desktop/daemon is not running.
    echo [X] Start Docker and rerun run.bat.
    goto :db_ready
)

echo [*] Starting PostgreSQL in Docker...
set "PG_CONTAINER=secureguard-postgres"
set "PG_EXISTS="
for /f %%N in ('docker ps -a --format "{{.Names}}" ^| findstr /R /X /C:"!PG_CONTAINER!"') do (
    set "PG_EXISTS=1"
)

if defined PG_EXISTS (
    docker start "!PG_CONTAINER!" >nul 2>&1
) else (
    docker run -d --name "!PG_CONTAINER!" -e POSTGRES_USER=!DB_USER! -e POSTGRES_PASSWORD=!DB_PASSWORD! -e POSTGRES_DB=!DB_NAME! -p !DB_PORT!:5432 postgres:16-alpine >nul
)

for /l %%I in (1,1,30) do (
    for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":!DB_PORT! .*LISTENING"') do (
        set "DB_READY=1"
        goto :db_wait_done
    )
    timeout /t 1 /nobreak >nul
)

:db_wait_done
if not defined DB_READY (
    echo [X] PostgreSQL did not become ready on !DB_HOST!:!DB_PORT!.
    goto :db_ready
)

if exist "%SCHEMA_FILE%" (
    echo [*] Applying DB schema...
    docker exec -i "!PG_CONTAINER!" psql -U "!DB_USER!" -d "!DB_NAME!" < "%SCHEMA_FILE%" >nul 2>&1
    if errorlevel 1 (
        echo [!] Could not auto-apply schema. You can apply it manually:
        echo     psql -U !DB_USER! -d !DB_NAME! -f server\migrations\scheme\sqlc.sql
    )
)

:db_ready
if not defined DB_READY (
    echo [X] Database is not ready. Backend start canceled.
    pause
    exit /b 1
)
echo [+] Database is ready.

if defined REDIS_REQUIRED (
    call :ensure_redis
    if errorlevel 1 (
        pause
        exit /b 1
    )
) else (
    echo [*] Redis rate limit is disabled in backend config.
)

echo [*] Starting backend in a separate window...
start "SecureGuard Backend" cmd /k "set REDIS_ADDR=!REDIS_EFFECTIVE_ADDR! && cd /d ""%SERVER_DIR%"" && go run ."
set "BACKEND_RUNNING=1"
timeout /t 2 /nobreak >nul

:after_backend
if defined RUN_CLIENT if not defined BACKEND_RUNNING (
    echo [!] Client will use %BACKEND_ENDPOINT%.
    echo [!] Start backend separately if you need live API calls.
)

if not defined RUN_CLIENT goto :done

cd /d "%CLIENT_DIR%" || (
    echo [X] Failed to access client directory.
    pause
    exit /b 1
)

if not exist "node_modules\" (
    echo [*] Installing npm dependencies...
    if exist "package-lock.json" (
        call npm ci
    ) else (
        call npm install
    )

    if errorlevel 1 (
        echo [X] npm install failed.
        pause
        exit /b 1
    )
    echo [+] Dependencies installed.
)

echo.
echo  Starting SecureGuard client...
echo.
echo  [DEV]   npm run dev
echo  [BUILD] npm run build
echo.

set "MODE="
set /p MODE="Mode (dev/build): "
if not defined MODE set "MODE=dev"

set "SECUREGUARD_GRPC_ENDPOINT=%BACKEND_ENDPOINT%"
set "SECUREGUARD_BACKEND=%BACKEND_ENDPOINT%"

cls

if /i "%MODE%"=="build" (
    echo  SecureGuard - BUILD
    echo.
    echo [*] Building release EXE...
    echo [*] Backend endpoint for local runs: %SECUREGUARD_GRPC_ENDPOINT%
    echo.
    call npm run build

    if errorlevel 1 (
        echo [X] Build failed.
        pause
        exit /b 1
    )

    echo.
    echo [+] BUILD SUCCESS
    echo [+] EXE:       src-tauri\target\release\
    echo [+] Installer: src-tauri\target\release\bundle\nsis\
    echo.

    set "OPEN="
    set /p OPEN="Open folder? (y/n): "
    if /i "%OPEN%"=="y" explorer "src-tauri\target\release"
) else (
    echo  ==================================
    echo   SecureGuard - DEV
    echo  ==================================
    echo.
    echo [*] Using backend: %SECUREGUARD_GRPC_ENDPOINT%
    echo [*] Starting dev mode...
    echo.
    call npm run dev
)

:done
pause
exit /b 0

:ensure_redis
echo [*] Checking Redis...

if not defined REDIS_LOCAL (
    echo [*] Using remote Redis !REDIS_EFFECTIVE_ADDR!
    echo [+] Redis is ready.
    exit /b 0
)

for /f "tokens=5" %%P in ('netstat -ano ^| findstr /R /C:":!REDIS_PORT! .*LISTENING"') do (
    echo [+] Redis is ready.
    exit /b 0
)

where docker >nul 2>&1
if errorlevel 1 (
    echo [X] Redis is not listening on !REDIS_EFFECTIVE_ADDR! and Docker is not installed.
    echo [X] Start Redis manually and rerun run.bat.
    exit /b 1
)

docker info >nul 2>&1
if errorlevel 1 (
    echo [X] Docker is installed, but Docker Desktop/daemon is not running.
    echo [X] Start Docker and rerun run.bat.
    exit /b 1
)

echo [*] Starting Redis in Docker...
set "REDIS_CONTAINER=secureguard-redis"
set "REDIS_EXISTS="
for /f %%N in ('docker ps -a --format "{{.Names}}" ^| findstr /R /X /C:"!REDIS_CONTAINER!"') do (
    set "REDIS_EXISTS=1"
)

if defined REDIS_EXISTS (
    docker start "!REDIS_CONTAINER!" >nul 2>&1
) else (
    docker run -d --name "!REDIS_CONTAINER!" -p !REDIS_PORT!:6379 redis:7-alpine redis-server --appendonly yes --save 60 1000 >nul
)

for /l %%I in (1,1,30) do (
    docker exec "!REDIS_CONTAINER!" redis-cli ping 2>nul | findstr /I /C:"PONG" >nul
    if not errorlevel 1 (
        echo [+] Redis is ready.
        exit /b 0
    )
    timeout /t 1 /nobreak >nul
)

echo [X] Redis did not become ready on !REDIS_EFFECTIVE_ADDR!.
echo [X] Redis is not ready. Backend start canceled.
exit /b 1
