// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/passwords/v1/domain.proto

package passwords

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Password struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serv          *ServiceInfo           `protobuf:"bytes,1,opt,name=serv,proto3" json:"serv,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Pass          string                 `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Password) GetServ() *ServiceInfo {
	if x != nil {
		return x.Serv
	}
	return nil
}

func (x *Password) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Password) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *Password) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Password            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetList() []*Password {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceUrl    string                 `protobuf:"bytes,1,opt,name=service_url,json=serviceUrl,proto3" json:"service_url,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         string                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Aad           []byte                 `protobuf:"bytes,6,opt,name=aad,proto3" json:"aad,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

func (x *CreateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateRequest) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *CreateRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CreateRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *CreateRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type PassDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *Password              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassDataResponse) Reset() {
	*x = PassDataResponse{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassDataResponse) ProtoMessage() {}

func (x *PassDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassDataResponse.ProtoReflect.Descriptor instead.
func (*PassDataResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{4}
}

func (x *PassDataResponse) GetInfo() *Password {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *PassDataResponse) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceUrl    *string                `protobuf:"bytes,2,opt,name=service_url,json=serviceUrl,proto3,oneof" json:"service_url,omitempty"`
	Login         *string                `protobuf:"bytes,3,opt,name=login,proto3,oneof" json:"login,omitempty"`
	Pass          *string                `protobuf:"bytes,4,opt,name=pass,proto3,oneof" json:"pass,omitempty"`
	Salt          string                 `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetServiceUrl() string {
	if x != nil && x.ServiceUrl != nil {
		return *x.ServiceUrl
	}
	return ""
}

func (x *UpdateRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *UpdateRequest) GetPass() string {
	if x != nil && x.Pass != nil {
		return *x.Pass
	}
	return ""
}

func (x *UpdateRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP(), []int{6}
}

var File_xyz_secureguard_v1_passwords_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDesc = "" +
	"\n" +
	",xyz/secureguard/v1/passwords/v1/domain.proto\x12\x1fxyz.secureguard.v1.passwords.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\vServiceInfo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb1\x01\n" +
	"\bPassword\x12@\n" +
	"\x04serv\x18\x01 \x01(\v2,.xyz.secureguard.v1.passwords.v1.ServiceInfoR\x04serv\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\tR\x04pass\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\fListResponse\x12=\n" +
	"\x04list\x18\x01 \x03(\v2).xyz.secureguard.v1.passwords.v1.PasswordR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xc4\x01\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\vservice_url\x18\x01 \x01(\tR\n" +
	"serviceUrl\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\tR\n" +
	"ciphertext\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\x12\x10\n" +
	"\x03aad\x18\x06 \x01(\fR\x03aad\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"}\n" +
	"\x10PassDataResponse\x12=\n" +
	"\x04info\x18\x01 \x01(\v2).xyz.secureguard.v1.passwords.v1.PasswordR\x04info\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xb0\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\vservice_url\x18\x02 \x01(\tH\x00R\n" +
	"serviceUrl\x88\x01\x01\x12\x19\n" +
	"\x05login\x18\x03 \x01(\tH\x01R\x05login\x88\x01\x01\x12\x17\n" +
	"\x04pass\x18\x04 \x01(\tH\x02R\x04pass\x88\x01\x01\x12\x12\n" +
	"\x04salt\x18\x05 \x01(\tR\x04saltB\x0e\n" +
	"\f_service_urlB\b\n" +
	"\x06_loginB\a\n" +
	"\x05_pass\"\x10\n" +
	"\x0eDeleteResponseBIZGgithub.com/aesterial/secureguard/internal/api/v1/passwords/v1;passwordsb\x06proto3"

var (
	file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xyz_secureguard_v1_passwords_v1_domain_proto_goTypes = []any{
	(*ServiceInfo)(nil),           // 0: xyz.secureguard.v1.passwords.v1.ServiceInfo
	(*Password)(nil),              // 1: xyz.secureguard.v1.passwords.v1.Password
	(*ListResponse)(nil),          // 2: xyz.secureguard.v1.passwords.v1.ListResponse
	(*CreateRequest)(nil),         // 3: xyz.secureguard.v1.passwords.v1.CreateRequest
	(*PassDataResponse)(nil),      // 4: xyz.secureguard.v1.passwords.v1.PassDataResponse
	(*UpdateRequest)(nil),         // 5: xyz.secureguard.v1.passwords.v1.UpdateRequest
	(*DeleteResponse)(nil),        // 6: xyz.secureguard.v1.passwords.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_passwords_v1_domain_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.v1.passwords.v1.Password.serv:type_name -> xyz.secureguard.v1.passwords.v1.ServiceInfo
	7, // 1: xyz.secureguard.v1.passwords.v1.Password.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: xyz.secureguard.v1.passwords.v1.ListResponse.list:type_name -> xyz.secureguard.v1.passwords.v1.Password
	1, // 3: xyz.secureguard.v1.passwords.v1.PassDataResponse.info:type_name -> xyz.secureguard.v1.passwords.v1.Password
	7, // 4: xyz.secureguard.v1.passwords.v1.PassDataResponse.at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_passwords_v1_domain_proto_init() }
func file_xyz_secureguard_v1_passwords_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_passwords_v1_domain_proto != nil {
		return
	}
	file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_passwords_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_passwords_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_passwords_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_passwords_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_passwords_v1_domain_proto = out.File
	file_xyz_secureguard_v1_passwords_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_passwords_v1_domain_proto_depIdxs = nil
}
