// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/passwords/v1/service.proto

package passwords

import (
	v1 "github.com/aesterial/secureguard/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_passwords_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_passwords_v1_service_proto_rawDesc = "" +
	"\n" +
	"-xyz/secureguard/v1/passwords/v1/service.proto\x12\x1fxyz.secureguard.v1.passwords.v1\x1a,xyz/secureguard/v1/passwords/v1/domain.proto\x1a\x1exyz/secureguard/v1/types.proto2\xaf\x03\n" +
	"\x0fPasswordService\x12d\n" +
	"\x04List\x12-.xyz.secureguard.v1.RequestWithLimitAndOffset\x1a-.xyz.secureguard.v1.passwords.v1.ListResponse\x12k\n" +
	"\x06Create\x12..xyz.secureguard.v1.passwords.v1.CreateRequest\x1a1.xyz.secureguard.v1.passwords.v1.PassDataResponse\x12k\n" +
	"\x06Update\x12..xyz.secureguard.v1.passwords.v1.UpdateRequest\x1a1.xyz.secureguard.v1.passwords.v1.PassDataResponse\x12\\\n" +
	"\x06Delete\x12!.xyz.secureguard.v1.RequestWithID\x1a/.xyz.secureguard.v1.passwords.v1.DeleteResponseBIZGgithub.com/aesterial/secureguard/internal/api/v1/passwords/v1;passwordsb\x06proto3"

var file_xyz_secureguard_v1_passwords_v1_service_proto_goTypes = []any{
	(*v1.RequestWithLimitAndOffset)(nil), // 0: xyz.secureguard.v1.RequestWithLimitAndOffset
	(*CreateRequest)(nil),                // 1: xyz.secureguard.v1.passwords.v1.CreateRequest
	(*UpdateRequest)(nil),                // 2: xyz.secureguard.v1.passwords.v1.UpdateRequest
	(*v1.RequestWithID)(nil),             // 3: xyz.secureguard.v1.RequestWithID
	(*ListResponse)(nil),                 // 4: xyz.secureguard.v1.passwords.v1.ListResponse
	(*PassDataResponse)(nil),             // 5: xyz.secureguard.v1.passwords.v1.PassDataResponse
	(*DeleteResponse)(nil),               // 6: xyz.secureguard.v1.passwords.v1.DeleteResponse
}
var file_xyz_secureguard_v1_passwords_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.v1.passwords.v1.PasswordService.List:input_type -> xyz.secureguard.v1.RequestWithLimitAndOffset
	1, // 1: xyz.secureguard.v1.passwords.v1.PasswordService.Create:input_type -> xyz.secureguard.v1.passwords.v1.CreateRequest
	2, // 2: xyz.secureguard.v1.passwords.v1.PasswordService.Update:input_type -> xyz.secureguard.v1.passwords.v1.UpdateRequest
	3, // 3: xyz.secureguard.v1.passwords.v1.PasswordService.Delete:input_type -> xyz.secureguard.v1.RequestWithID
	4, // 4: xyz.secureguard.v1.passwords.v1.PasswordService.List:output_type -> xyz.secureguard.v1.passwords.v1.ListResponse
	5, // 5: xyz.secureguard.v1.passwords.v1.PasswordService.Create:output_type -> xyz.secureguard.v1.passwords.v1.PassDataResponse
	5, // 6: xyz.secureguard.v1.passwords.v1.PasswordService.Update:output_type -> xyz.secureguard.v1.passwords.v1.PassDataResponse
	6, // 7: xyz.secureguard.v1.passwords.v1.PasswordService.Delete:output_type -> xyz.secureguard.v1.passwords.v1.DeleteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_passwords_v1_service_proto_init() }
func file_xyz_secureguard_v1_passwords_v1_service_proto_init() {
	if File_xyz_secureguard_v1_passwords_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_passwords_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_passwords_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_passwords_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_passwords_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_passwords_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_passwords_v1_service_proto = out.File
	file_xyz_secureguard_v1_passwords_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_passwords_v1_service_proto_depIdxs = nil
}
