// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: xyz/secureguard/v1/users/v1/service.proto

package users

import (
	context "context"
	v1 "github.com/aesterial/secureguard/internal/api/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_Info_FullMethodName           = "/xyz.secureguard.v1.users.v1.UserService/Info"
	UserService_ChangeTheme_FullMethodName    = "/xyz.secureguard.v1.users.v1.UserService/ChangeTheme"
	UserService_ChangeLanguage_FullMethodName = "/xyz.secureguard.v1.users.v1.UserService/ChangeLanguage"
	UserService_ChangeCrypt_FullMethodName    = "/xyz.secureguard.v1.users.v1.UserService/ChangeCrypt"
	UserService_ChangeKey_FullMethodName      = "/xyz.secureguard.v1.users.v1.UserService/ChangeKey"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error)
	ChangeTheme(ctx context.Context, in *ChangeThemeRequest, opts ...grpc.CallOption) (*ChangeThemeResponse, error)
	ChangeLanguage(ctx context.Context, in *ChangeLanguageRequest, opts ...grpc.CallOption) (*ChangeLanguageResponse, error)
	ChangeCrypt(ctx context.Context, in *ChangeCryptRequest, opts ...grpc.CallOption) (*ChangeCryptResponse, error)
	ChangeKey(ctx context.Context, in *v1.RequestWithValueAndKdf, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeTheme(ctx context.Context, in *ChangeThemeRequest, opts ...grpc.CallOption) (*ChangeThemeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeThemeResponse)
	err := c.cc.Invoke(ctx, UserService_ChangeTheme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeLanguage(ctx context.Context, in *ChangeLanguageRequest, opts ...grpc.CallOption) (*ChangeLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeLanguageResponse)
	err := c.cc.Invoke(ctx, UserService_ChangeLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeCrypt(ctx context.Context, in *ChangeCryptRequest, opts ...grpc.CallOption) (*ChangeCryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeCryptResponse)
	err := c.cc.Invoke(ctx, UserService_ChangeCrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeKey(ctx context.Context, in *v1.RequestWithValueAndKdf, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_ChangeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations should embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	Info(context.Context, *emptypb.Empty) (*UserResponse, error)
	ChangeTheme(context.Context, *ChangeThemeRequest) (*ChangeThemeResponse, error)
	ChangeLanguage(context.Context, *ChangeLanguageRequest) (*ChangeLanguageResponse, error)
	ChangeCrypt(context.Context, *ChangeCryptRequest) (*ChangeCryptResponse, error)
	ChangeKey(context.Context, *v1.RequestWithValueAndKdf) (*emptypb.Empty, error)
}

// UnimplementedUserServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) Info(context.Context, *emptypb.Empty) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedUserServiceServer) ChangeTheme(context.Context, *ChangeThemeRequest) (*ChangeThemeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeTheme not implemented")
}
func (UnimplementedUserServiceServer) ChangeLanguage(context.Context, *ChangeLanguageRequest) (*ChangeLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeLanguage not implemented")
}
func (UnimplementedUserServiceServer) ChangeCrypt(context.Context, *ChangeCryptRequest) (*ChangeCryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeCrypt not implemented")
}
func (UnimplementedUserServiceServer) ChangeKey(context.Context, *v1.RequestWithValueAndKdf) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeKey not implemented")
}
func (UnimplementedUserServiceServer) testEmbeddedByValue() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Info(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeTheme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeThemeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeTheme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangeTheme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeTheme(ctx, req.(*ChangeThemeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangeLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeLanguage(ctx, req.(*ChangeLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeCrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeCryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeCrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangeCrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeCrypt(ctx, req.(*ChangeCryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RequestWithValueAndKdf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeKey(ctx, req.(*v1.RequestWithValueAndKdf))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.secureguard.v1.users.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _UserService_Info_Handler,
		},
		{
			MethodName: "ChangeTheme",
			Handler:    _UserService_ChangeTheme_Handler,
		},
		{
			MethodName: "ChangeLanguage",
			Handler:    _UserService_ChangeLanguage_Handler,
		},
		{
			MethodName: "ChangeCrypt",
			Handler:    _UserService_ChangeCrypt_Handler,
		},
		{
			MethodName: "ChangeKey",
			Handler:    _UserService_ChangeKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xyz/secureguard/v1/users/v1/service.proto",
}
