// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/users/v1/service.proto

package users

import (
	v1 "github.com/aesterial/secureguard/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_users_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_users_v1_service_proto_rawDesc = "" +
	"\n" +
	")xyz/secureguard/v1/users/v1/service.proto\x12\x1bxyz.secureguard.v1.users.v1\x1a\x1exyz/secureguard/v1/types.proto\x1a(xyz/secureguard/v1/users/v1/domain.proto\x1a\x1bgoogle/protobuf/empty.proto2\xea\x04\n" +
	"\vUserService\x12I\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a).xyz.secureguard.v1.users.v1.UserResponse\x12`\n" +
	"\x04List\x12-.xyz.secureguard.v1.RequestWithLimitAndOffset\x1a).xyz.secureguard.v1.users.v1.ListResponse\x12p\n" +
	"\vChangeTheme\x12/.xyz.secureguard.v1.users.v1.ChangeThemeRequest\x1a0.xyz.secureguard.v1.users.v1.ChangeThemeResponse\x12y\n" +
	"\x0eChangeLanguage\x122.xyz.secureguard.v1.users.v1.ChangeLanguageRequest\x1a3.xyz.secureguard.v1.users.v1.ChangeLanguageResponse\x12p\n" +
	"\vChangeCrypt\x12/.xyz.secureguard.v1.users.v1.ChangeCryptRequest\x1a0.xyz.secureguard.v1.users.v1.ChangeCryptResponse\x12O\n" +
	"\tChangeKey\x12*.xyz.secureguard.v1.RequestWithValueAndKdf\x1a\x16.google.protobuf.EmptyBAZ?github.com/aesterial/secureguard/internal/api/v1/users/v1;usersb\x06proto3"

var file_xyz_secureguard_v1_users_v1_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                // 0: google.protobuf.Empty
	(*v1.RequestWithLimitAndOffset)(nil), // 1: xyz.secureguard.v1.RequestWithLimitAndOffset
	(*ChangeThemeRequest)(nil),           // 2: xyz.secureguard.v1.users.v1.ChangeThemeRequest
	(*ChangeLanguageRequest)(nil),        // 3: xyz.secureguard.v1.users.v1.ChangeLanguageRequest
	(*ChangeCryptRequest)(nil),           // 4: xyz.secureguard.v1.users.v1.ChangeCryptRequest
	(*v1.RequestWithValueAndKdf)(nil),    // 5: xyz.secureguard.v1.RequestWithValueAndKdf
	(*UserResponse)(nil),                 // 6: xyz.secureguard.v1.users.v1.UserResponse
	(*ListResponse)(nil),                 // 7: xyz.secureguard.v1.users.v1.ListResponse
	(*ChangeThemeResponse)(nil),          // 8: xyz.secureguard.v1.users.v1.ChangeThemeResponse
	(*ChangeLanguageResponse)(nil),       // 9: xyz.secureguard.v1.users.v1.ChangeLanguageResponse
	(*ChangeCryptResponse)(nil),          // 10: xyz.secureguard.v1.users.v1.ChangeCryptResponse
}
var file_xyz_secureguard_v1_users_v1_service_proto_depIdxs = []int32{
	0,  // 0: xyz.secureguard.v1.users.v1.UserService.Info:input_type -> google.protobuf.Empty
	1,  // 1: xyz.secureguard.v1.users.v1.UserService.List:input_type -> xyz.secureguard.v1.RequestWithLimitAndOffset
	2,  // 2: xyz.secureguard.v1.users.v1.UserService.ChangeTheme:input_type -> xyz.secureguard.v1.users.v1.ChangeThemeRequest
	3,  // 3: xyz.secureguard.v1.users.v1.UserService.ChangeLanguage:input_type -> xyz.secureguard.v1.users.v1.ChangeLanguageRequest
	4,  // 4: xyz.secureguard.v1.users.v1.UserService.ChangeCrypt:input_type -> xyz.secureguard.v1.users.v1.ChangeCryptRequest
	5,  // 5: xyz.secureguard.v1.users.v1.UserService.ChangeKey:input_type -> xyz.secureguard.v1.RequestWithValueAndKdf
	6,  // 6: xyz.secureguard.v1.users.v1.UserService.Info:output_type -> xyz.secureguard.v1.users.v1.UserResponse
	7,  // 7: xyz.secureguard.v1.users.v1.UserService.List:output_type -> xyz.secureguard.v1.users.v1.ListResponse
	8,  // 8: xyz.secureguard.v1.users.v1.UserService.ChangeTheme:output_type -> xyz.secureguard.v1.users.v1.ChangeThemeResponse
	9,  // 9: xyz.secureguard.v1.users.v1.UserService.ChangeLanguage:output_type -> xyz.secureguard.v1.users.v1.ChangeLanguageResponse
	10, // 10: xyz.secureguard.v1.users.v1.UserService.ChangeCrypt:output_type -> xyz.secureguard.v1.users.v1.ChangeCryptResponse
	0,  // 11: xyz.secureguard.v1.users.v1.UserService.ChangeKey:output_type -> google.protobuf.Empty
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_users_v1_service_proto_init() }
func file_xyz_secureguard_v1_users_v1_service_proto_init() {
	if File_xyz_secureguard_v1_users_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_users_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_users_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_users_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_users_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_users_v1_service_proto = out.File
	file_xyz_secureguard_v1_users_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_users_v1_service_proto_depIdxs = nil
}
