// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Password struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	PhrasePass bool               `json:"phrase_pass"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	Username   string             `json:"username"`
	Password   string             `json:"password"`
	SeedPhrase pgtype.Text        `json:"seed_phrase"`
	Joined     pgtype.Timestamptz `json:"joined"`
}
