// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID        pgtype.UUID        `json:"id"`
	Users     int32              `json:"users"`
	Registers int32              `json:"registers"`
	At        pgtype.Timestamptz `json:"at"`
}

type Password struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	Service    string             `json:"service"`
	Login      string             `json:"login"`
	Ciphertext string             `json:"ciphertext"`
	Version    int32              `json:"version"`
	Nonce      string             `json:"nonce"`
	Aad        []byte             `json:"aad"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Preference struct {
	Owner pgtype.UUID `json:"owner"`
	Theme string      `json:"theme"`
	Lang  string      `json:"lang"`
	Crypt string      `json:"crypt"`
}

type Session struct {
	ID         string             `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Revoked    bool               `json:"revoked"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	Created    pgtype.Timestamptz `json:"created"`
	Expires    pgtype.Timestamptz `json:"expires"`
	LastSeen   pgtype.Timestamptz `json:"last_seen"`
}

type Statistic struct {
	ID          pgtype.UUID        `json:"id"`
	P50         float64            `json:"p50"`
	P90         float64            `json:"p90"`
	ServicesTop []byte             `json:"services_top"`
	CryptUses   []byte             `json:"crypt_uses"`
	At          pgtype.Timestamptz `json:"at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Password    string             `json:"password"`
	AdminAccess bool               `json:"admin_access"`
	Joined      pgtype.Timestamptz `json:"joined"`
}

type UsersKey struct {
	Owner       pgtype.UUID `json:"owner"`
	MasterKey   string      `json:"master_key"`
	Salt        string      `json:"salt"`
	Version     int32       `json:"version"`
	Memory      int64       `json:"memory"`
	Iterations  int32       `json:"iterations"`
	Parallelism int32       `json:"parallelism"`
}
