// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Password struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Service   string             `json:"service"`
	Login     string             `json:"login"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Preference struct {
	Owner pgtype.UUID `json:"owner"`
	Theme string      `json:"theme"`
	Lang  string      `json:"lang"`
	Crypt string      `json:"crypt"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Revoked    bool               `json:"revoked"`
	Created    pgtype.Timestamptz `json:"created"`
	Expires    pgtype.Timestamptz `json:"expires"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	Username   string             `json:"username"`
	Password   string             `json:"password"`
	SeedPhrase string             `json:"seed_phrase"`
	Joined     pgtype.Timestamptz `json:"joined"`
}
