// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersRegisteredBetween = `-- name: CountUsersRegisteredBetween :one
select COUNT(*)
from users
where joined >= $1 and joined < $2
`

type CountUsersRegisteredBetweenParams struct {
	Joined   pgtype.Timestamptz `json:"joined"`
	Joined_2 pgtype.Timestamptz `json:"joined_2"`
}

func (q *Queries) CountUsersRegisteredBetween(ctx context.Context, arg CountUsersRegisteredBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersRegisteredBetween, arg.Joined, arg.Joined_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivitySnapshot = `-- name: CreateActivitySnapshot :exec
insert into activity (
    users,
    registers,
    at
)
select $1, $2, $3
where not exists (
    select 1 from activity where at = $3
)
`

type CreateActivitySnapshotParams struct {
	Users     int32              `json:"users"`
	Registers int32              `json:"registers"`
	At        pgtype.Timestamptz `json:"at"`
}

func (q *Queries) CreateActivitySnapshot(ctx context.Context, arg CreateActivitySnapshotParams) error {
	_, err := q.db.Exec(ctx, createActivitySnapshot, arg.Users, arg.Registers, arg.At)
	return err
}

const createPassword = `-- name: CreatePassword :one
insert into passwords (
    owner,
    service,
    login,
    pass,
    salt
)
values ($1, $2, $3, $4, $5)
returning id, owner, service, login, pass, salt, created_at
`

type CreatePasswordParams struct {
	Owner   pgtype.UUID `json:"owner"`
	Service string      `json:"service"`
	Login   string      `json:"login"`
	Pass    string      `json:"pass"`
	Salt    string      `json:"salt"`
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error) {
	row := q.db.QueryRow(ctx, createPassword,
		arg.Owner,
		arg.Service,
		arg.Login,
		arg.Pass,
		arg.Salt,
	)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Service,
		&i.Login,
		&i.Pass,
		&i.Salt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into sessions (owner, client_hash) values ($1, $2) returning id
`

type CreateSessionParams struct {
	Owner      pgtype.UUID `json:"owner"`
	ClientHash string      `json:"client_hash"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Owner, arg.ClientHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createStatisticsSnapshot = `-- name: CreateStatisticsSnapshot :exec
insert into statistics (
    p50,
    p90,
    services_top,
    crypt_uses,
    at
)
select $1, $2, $3, $4, $5
where not exists (
    select 1 from statistics where at = $5
)
`

type CreateStatisticsSnapshotParams struct {
	P50         float64            `json:"p50"`
	P90         float64            `json:"p90"`
	ServicesTop []byte             `json:"services_top"`
	CryptUses   []byte             `json:"crypt_uses"`
	At          pgtype.Timestamptz `json:"at"`
}

func (q *Queries) CreateStatisticsSnapshot(ctx context.Context, arg CreateStatisticsSnapshotParams) error {
	_, err := q.db.Exec(ctx, createStatisticsSnapshot,
		arg.P50,
		arg.P90,
		arg.ServicesTop,
		arg.CryptUses,
		arg.At,
	)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (
    username,
    password,
    seed_phrase
)
values ($1, $2, $3)
returning id, username, password, seed_phrase, admin_access, joined
`

type CreateUserParams struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	SeedPhrase string `json:"seed_phrase"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.SeedPhrase)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.AdminAccess,
		&i.Joined,
	)
	return i, err
}

const deletePassword = `-- name: DeletePassword :exec
delete from passwords where id = $1
`

func (q *Queries) DeletePassword(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePassword, id)
	return err
}

const getActivityStatistics = `-- name: GetActivityStatistics :many
select users, registers, at from activity where at >= $1 AND at < $2
`

type GetActivityStatisticsParams struct {
	At   pgtype.Timestamptz `json:"at"`
	At_2 pgtype.Timestamptz `json:"at_2"`
}

type GetActivityStatisticsRow struct {
	Users     int32              `json:"users"`
	Registers int32              `json:"registers"`
	At        pgtype.Timestamptz `json:"at"`
}

func (q *Queries) GetActivityStatistics(ctx context.Context, arg GetActivityStatisticsParams) ([]GetActivityStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getActivityStatistics, arg.At, arg.At_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivityStatisticsRow{}
	for rows.Next() {
		var i GetActivityStatisticsRow
		if err := rows.Scan(&i.Users, &i.Registers, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChoosenPreferencesCrypt = `-- name: GetChoosenPreferencesCrypt :many
select crypt from preferences
`

func (q *Queries) GetChoosenPreferencesCrypt(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getChoosenPreferencesCrypt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var crypt string
		if err := rows.Scan(&crypt); err != nil {
			return nil, err
		}
		items = append(items, crypt)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChoosenPreferencesLanguage = `-- name: GetChoosenPreferencesLanguage :many
select lang from preferences
`

func (q *Queries) GetChoosenPreferencesLanguage(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getChoosenPreferencesLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lang string
		if err := rows.Scan(&lang); err != nil {
			return nil, err
		}
		items = append(items, lang)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChoosenPreferencesTheme = `-- name: GetChoosenPreferencesTheme :many
select theme from preferences
`

func (q *Queries) GetChoosenPreferencesTheme(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getChoosenPreferencesTheme)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var theme string
		if err := rows.Scan(&theme); err != nil {
			return nil, err
		}
		items = append(items, theme)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
select id from sessions where expires < now()
`

func (q *Queries) GetExpiredSessions(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIsUserAdmin = `-- name: GetIsUserAdmin :one
select admin_access = true from users where id = $1 limit 1
`

func (q *Queries) GetIsUserAdmin(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUserAdmin, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getIsUserExists = `-- name: GetIsUserExists :one
select exists (select 1 from users where id = $1)
`

func (q *Queries) GetIsUserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIsUsernameExists = `-- name: GetIsUsernameExists :one
select exists (select 1 from users where username = $1)
`

func (q *Queries) GetIsUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getListUsers = `-- name: GetListUsers :many
select id, username, password, seed_phrase, admin_access, joined
from users
order by joined desc
limit $1
offset $2
`

type GetListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetListUsers(ctx context.Context, arg GetListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.SeedPhrase,
			&i.AdminAccess,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordByID = `-- name: GetPasswordByID :one
select id, owner, service, login, pass, created_at
from passwords
where id = $1
limit 1
`

type GetPasswordByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Service   string             `json:"service"`
	Login     string             `json:"login"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPasswordByID(ctx context.Context, id pgtype.UUID) (GetPasswordByIDRow, error) {
	row := q.db.QueryRow(ctx, getPasswordByID, id)
	var i GetPasswordByIDRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Service,
		&i.Login,
		&i.Pass,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordOwner = `-- name: GetPasswordOwner :one
select owner from passwords where id = $1 limit 1
`

func (q *Queries) GetPasswordOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPasswordOwner, id)
	var owner pgtype.UUID
	err := row.Scan(&owner)
	return owner, err
}

const getSavedStatsLatency = `-- name: GetSavedStatsLatency :one
select p50, p90 from statistics where at = $1 limit 1
`

type GetSavedStatsLatencyRow struct {
	P50 float64 `json:"p50"`
	P90 float64 `json:"p90"`
}

func (q *Queries) GetSavedStatsLatency(ctx context.Context, at pgtype.Timestamptz) (GetSavedStatsLatencyRow, error) {
	row := q.db.QueryRow(ctx, getSavedStatsLatency, at)
	var i GetSavedStatsLatencyRow
	err := row.Scan(&i.P50, &i.P90)
	return i, err
}

const getServicesTopStats = `-- name: GetServicesTopStats :one
select services_top from statistics where at = $1 limit 1
`

func (q *Queries) GetServicesTopStats(ctx context.Context, at pgtype.Timestamptz) ([]byte, error) {
	row := q.db.QueryRow(ctx, getServicesTopStats, at)
	var services_top []byte
	err := row.Scan(&services_top)
	return services_top, err
}

const getSessionByID = `-- name: GetSessionByID :one
select id, owner, client_hash, created, revoked
from sessions
where id = $1
limit 1
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
	Revoked    bool               `json:"revoked"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.ClientHash,
		&i.Created,
		&i.Revoked,
	)
	return i, err
}

const getSessionInfo = `-- name: GetSessionInfo :one
select owner, client_hash, revoked, created, expires from sessions where id = $1 limit 1
`

type GetSessionInfoRow struct {
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Revoked    bool               `json:"revoked"`
	Created    pgtype.Timestamptz `json:"created"`
	Expires    pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) GetSessionInfo(ctx context.Context, id pgtype.UUID) (GetSessionInfoRow, error) {
	row := q.db.QueryRow(ctx, getSessionInfo, id)
	var i GetSessionInfoRow
	err := row.Scan(
		&i.Owner,
		&i.ClientHash,
		&i.Revoked,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const getSessionOwner = `-- name: GetSessionOwner :one
select owner from sessions where id = $1 limit 1
`

func (q *Queries) GetSessionOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionOwner, id)
	var owner pgtype.UUID
	err := row.Scan(&owner)
	return owner, err
}

const getTotalActiveSessions = `-- name: GetTotalActiveSessions :one
select count(*) from sessions where not revoked and expires > now()
`

func (q *Queries) GetTotalActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalAdmins = `-- name: GetTotalAdmins :one
select COUNT(*) from users where admin_access = true limit 1
`

func (q *Queries) GetTotalAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPasswords = `-- name: GetTotalPasswords :one
select COUNT(*) from users limit 1
`

func (q *Queries) GetTotalPasswords(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPasswords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalUsers = `-- name: GetTotalUsers :one
select COUNT(*) from users limit 1
`

func (q *Queries) GetTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
select id, username, password, seed_phrase, admin_access, joined
from users
where id = $1
limit 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.AdminAccess,
		&i.Joined,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, password, seed_phrase, admin_access, joined
from users
where username = $1
limit 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.AdminAccess,
		&i.Joined,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
select password from users where id = $1 limit 1
`

func (q *Queries) GetUserPassword(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserPasswordByUsername = `-- name: GetUserPasswordByUsername :one
select password from users where username = $1 limit 1
`

func (q *Queries) GetUserPasswordByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordByUsername, username)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
select theme, lang from preferences where owner = $1 limit 1
`

type GetUserPreferencesRow struct {
	Theme string `json:"theme"`
	Lang  string `json:"lang"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, owner pgtype.UUID) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, owner)
	var i GetUserPreferencesRow
	err := row.Scan(&i.Theme, &i.Lang)
	return i, err
}

const initPreferences = `-- name: InitPreferences :exec
insert into preferences (owner) values ($1)
`

func (q *Queries) InitPreferences(ctx context.Context, owner pgtype.UUID) error {
	_, err := q.db.Exec(ctx, initPreferences, owner)
	return err
}

const isPasswordExists = `-- name: IsPasswordExists :one
select exists (select 1 from passwords where id = $1)
`

func (q *Queries) IsPasswordExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isPasswordExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isPreferencesExists = `-- name: IsPreferencesExists :one
select exists (select 1 from preferences where owner = $1)
`

func (q *Queries) IsPreferencesExists(ctx context.Context, owner pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isPreferencesExists, owner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSessionExists = `-- name: IsSessionExists :one
select exists (select 1 from sessions where id = $1)
`

func (q *Queries) IsSessionExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPasswordsByOwner = `-- name: ListPasswordsByOwner :many
select id, owner, service, login, pass, created_at
from passwords
where owner = $1
order by created_at desc
limit $2
offset $3
`

type ListPasswordsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListPasswordsByOwnerRow struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Service   string             `json:"service"`
	Login     string             `json:"login"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPasswordsByOwner(ctx context.Context, arg ListPasswordsByOwnerParams) ([]ListPasswordsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listPasswordsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPasswordsByOwnerRow{}
	for rows.Next() {
		var i ListPasswordsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Service,
			&i.Login,
			&i.Pass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOwner = `-- name: ListSessionsByOwner :many
select id, owner, client_hash, created, revoked
from sessions
where owner = $1
order by created desc
limit $2
offset $3
`

type ListSessionsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListSessionsByOwnerRow struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
	Revoked    bool               `json:"revoked"`
}

func (q *Queries) ListSessionsByOwner(ctx context.Context, arg ListSessionsByOwnerParams) ([]ListSessionsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByOwnerRow{}
	for rows.Next() {
		var i ListSessionsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.ClientHash,
			&i.Created,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked = true where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updatePasswordLogin = `-- name: UpdatePasswordLogin :exec
update passwords set login = $1, salt = $2 where id = $3
`

type UpdatePasswordLoginParams struct {
	Login string      `json:"login"`
	Salt  string      `json:"salt"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordLogin(ctx context.Context, arg UpdatePasswordLoginParams) error {
	_, err := q.db.Exec(ctx, updatePasswordLogin, arg.Login, arg.Salt, arg.ID)
	return err
}

const updatePasswordPass = `-- name: UpdatePasswordPass :exec
update passwords set pass = $1, salt = $2 where id = $3
`

type UpdatePasswordPassParams struct {
	Pass string      `json:"pass"`
	Salt string      `json:"salt"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordPass(ctx context.Context, arg UpdatePasswordPassParams) error {
	_, err := q.db.Exec(ctx, updatePasswordPass, arg.Pass, arg.Salt, arg.ID)
	return err
}

const updatePasswordService = `-- name: UpdatePasswordService :exec
update passwords set service = $1, salt = $2 where id = $3
`

type UpdatePasswordServiceParams struct {
	Service string      `json:"service"`
	Salt    string      `json:"salt"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordService(ctx context.Context, arg UpdatePasswordServiceParams) error {
	_, err := q.db.Exec(ctx, updatePasswordService, arg.Service, arg.Salt, arg.ID)
	return err
}

const updatePreferenceCrypt = `-- name: UpdatePreferenceCrypt :exec
update preferences set crypt = $1 where owner = $2
`

type UpdatePreferenceCryptParams struct {
	Crypt string      `json:"crypt"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceCrypt(ctx context.Context, arg UpdatePreferenceCryptParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceCrypt, arg.Crypt, arg.Owner)
	return err
}

const updatePreferenceLanguage = `-- name: UpdatePreferenceLanguage :exec
update preferences set lang = $1 where owner = $2
`

type UpdatePreferenceLanguageParams struct {
	Lang  string      `json:"lang"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceLanguage(ctx context.Context, arg UpdatePreferenceLanguageParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceLanguage, arg.Lang, arg.Owner)
	return err
}

const updatePreferenceTheme = `-- name: UpdatePreferenceTheme :exec
update preferences set theme = $1 where owner = $2
`

type UpdatePreferenceThemeParams struct {
	Theme string      `json:"theme"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceTheme(ctx context.Context, arg UpdatePreferenceThemeParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceTheme, arg.Theme, arg.Owner)
	return err
}

const updateSeedPhrase = `-- name: UpdateSeedPhrase :exec
update users set seed_phrase = $1 where id = $2
`

type UpdateSeedPhraseParams struct {
	SeedPhrase string      `json:"seed_phrase"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSeedPhrase(ctx context.Context, arg UpdateSeedPhraseParams) error {
	_, err := q.db.Exec(ctx, updateSeedPhrase, arg.SeedPhrase, arg.ID)
	return err
}
