// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePassword(ctx context.Context, arg DeletePasswordParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetPasswordByID(ctx context.Context, id pgtype.UUID) (Password, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListPasswordsByOwner(ctx context.Context, arg ListPasswordsByOwnerParams) ([]Password, error)
	ListSessionsByOwner(ctx context.Context, arg ListSessionsByOwnerParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
