// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPassword = `-- name: CreatePassword :one
insert into passwords (
    owner,
    pass
)
values ($1, $2)
returning id, owner, pass, created_at
`

type CreatePasswordParams struct {
	Owner pgtype.UUID `json:"owner"`
	Pass  string      `json:"pass"`
}

type CreatePasswordRow struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (CreatePasswordRow, error) {
	row := q.db.QueryRow(ctx, createPassword, arg.Owner, arg.Pass)
	var i CreatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Pass,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into sessions (
    owner,
    client_hash
)
values ($1, $2)
returning id, owner, client_hash, created
`

type CreateSessionParams struct {
	Owner      pgtype.UUID `json:"owner"`
	ClientHash string      `json:"client_hash"`
}

type CreateSessionRow struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Owner, arg.ClientHash)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.ClientHash,
		&i.Created,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (
    username,
    password,
    seed_phrase
)
values ($1, $2, $3)
returning id, username, password, seed_phrase, joined
`

type CreateUserParams struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	SeedPhrase string `json:"seed_phrase"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.SeedPhrase)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.Joined,
	)
	return i, err
}

const getIsUserExists = `-- name: GetIsUserExists :one
select exists (select 1 from users where id = $1)
`

func (q *Queries) GetIsUserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIsUsernameExists = `-- name: GetIsUsernameExists :one
select exists (select 1 from users where username = $1)
`

func (q *Queries) GetIsUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getListUsers = `-- name: GetListUsers :many
select id, username, password, seed_phrase, joined
from users
order by joined desc
limit $1
offset $2
`

type GetListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetListUsers(ctx context.Context, arg GetListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.SeedPhrase,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordByID = `-- name: GetPasswordByID :one
select id, owner, pass, created_at
from passwords
where id = $1
limit 1
`

type GetPasswordByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPasswordByID(ctx context.Context, id pgtype.UUID) (GetPasswordByIDRow, error) {
	row := q.db.QueryRow(ctx, getPasswordByID, id)
	var i GetPasswordByIDRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Pass,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
select id, owner, client_hash, created, revoked
from sessions
where id = $1
limit 1
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
	Revoked    bool               `json:"revoked"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.ClientHash,
		&i.Created,
		&i.Revoked,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, username, password, seed_phrase, joined
from users
where id = $1
limit 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.Joined,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, password, seed_phrase, joined
from users
where username = $1
limit 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.SeedPhrase,
		&i.Joined,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
select password from users where id = $1 limit 1
`

func (q *Queries) GetUserPassword(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
select theme, lang from preferences where owner = $1 limit 1
`

type GetUserPreferencesRow struct {
	Theme string `json:"theme"`
	Lang  string `json:"lang"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, owner pgtype.UUID) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, owner)
	var i GetUserPreferencesRow
	err := row.Scan(&i.Theme, &i.Lang)
	return i, err
}

const listPasswordsByOwner = `-- name: ListPasswordsByOwner :many
select id, owner, pass, created_at
from passwords
where owner = $1
order by created_at desc
limit $2
offset $3
`

type ListPasswordsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListPasswordsByOwnerRow struct {
	ID        pgtype.UUID        `json:"id"`
	Owner     pgtype.UUID        `json:"owner"`
	Pass      string             `json:"pass"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPasswordsByOwner(ctx context.Context, arg ListPasswordsByOwnerParams) ([]ListPasswordsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listPasswordsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPasswordsByOwnerRow{}
	for rows.Next() {
		var i ListPasswordsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Pass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOwner = `-- name: ListSessionsByOwner :many
select id, owner, client_hash, created, revoked
from sessions
where owner = $1
order by created desc
limit $2
offset $3
`

type ListSessionsByOwnerParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListSessionsByOwnerRow struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	ClientHash string             `json:"client_hash"`
	Created    pgtype.Timestamptz `json:"created"`
	Revoked    bool               `json:"revoked"`
}

func (q *Queries) ListSessionsByOwner(ctx context.Context, arg ListSessionsByOwnerParams) ([]ListSessionsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByOwner, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByOwnerRow{}
	for rows.Next() {
		var i ListSessionsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.ClientHash,
			&i.Created,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreferenceCrypt = `-- name: UpdatePreferenceCrypt :exec
update preferences set crypt = $1 where owner = $2
`

type UpdatePreferenceCryptParams struct {
	Crypt string      `json:"crypt"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceCrypt(ctx context.Context, arg UpdatePreferenceCryptParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceCrypt, arg.Crypt, arg.Owner)
	return err
}

const updatePreferenceLanguage = `-- name: UpdatePreferenceLanguage :exec
update preferences set lang = $1 where owner = $2
`

type UpdatePreferenceLanguageParams struct {
	Lang  string      `json:"lang"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceLanguage(ctx context.Context, arg UpdatePreferenceLanguageParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceLanguage, arg.Lang, arg.Owner)
	return err
}

const updatePreferenceTheme = `-- name: UpdatePreferenceTheme :exec
update preferences set theme = $1 where owner = $2
`

type UpdatePreferenceThemeParams struct {
	Theme string      `json:"theme"`
	Owner pgtype.UUID `json:"owner"`
}

func (q *Queries) UpdatePreferenceTheme(ctx context.Context, arg UpdatePreferenceThemeParams) error {
	_, err := q.db.Exec(ctx, updatePreferenceTheme, arg.Theme, arg.Owner)
	return err
}

const updateSeedPhrase = `-- name: UpdateSeedPhrase :exec
update users set seed_phrase = $1 where id = $2
`

type UpdateSeedPhraseParams struct {
	SeedPhrase string      `json:"seed_phrase"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSeedPhrase(ctx context.Context, arg UpdateSeedPhraseParams) error {
	_, err := q.db.Exec(ctx, updateSeedPhrase, arg.SeedPhrase, arg.ID)
	return err
}
