// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ByDateRequest {
    #[prost(message, optional, tag = "2")]
    pub day: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TotalResponse {
    #[prost(int32, tag = "1")]
    pub users: i32,
    #[prost(int32, tag = "2")]
    pub admins: i32,
    #[prost(int32, tag = "3")]
    pub passwords: i32,
    #[prost(int32, tag = "4")]
    pub active_sessions: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphPoint {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "2")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Latency {
    #[prost(double, tag = "1")]
    pub p50: f64,
    #[prost(double, tag = "2")]
    pub p90: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(map = "string, int32", tag = "1")]
    pub top_services: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(message, repeated, tag = "3")]
    pub users_graph: ::prost::alloc::vec::Vec<GraphPoint>,
    #[prost(message, repeated, tag = "2")]
    pub register_graph: ::prost::alloc::vec::Vec<GraphPoint>,
    #[prost(map = "string, int32", tag = "4")]
    pub crypt_uses: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(map = "string, int32", tag = "5")]
    pub theme_uses: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(map = "string, int32", tag = "6")]
    pub lang_uses: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(message, optional, tag = "7")]
    pub latency: ::core::option::Option<Latency>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<Stats>,
}
include!("stats.v1.tonic.rs");
// @@protoc_insertion_point(module)