// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ByDateRequest {
    #[prost(message, optional, tag = "2")]
    pub day: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TotalResponse {
    #[prost(int32, tag = "1")]
    pub users: i32,
    #[prost(int32, tag = "2")]
    pub admins: i32,
    #[prost(int32, tag = "3")]
    pub passwords: i32,
    #[prost(int32, tag = "4")]
    pub active_sessions: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphPoint {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag = "2")]
    pub value: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Latency {
    #[prost(double, tag = "1")]
    pub p50: f64,
    #[prost(double, tag = "2")]
    pub p90: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatsResponse {
    #[prost(map = "string, int32", tag = "1")]
    pub top_services: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(message, repeated, tag = "3")]
    pub activity_graph: ::prost::alloc::vec::Vec<GraphPoint>,
    #[prost(message, repeated, tag = "2")]
    pub register_graph: ::prost::alloc::vec::Vec<GraphPoint>,
    #[prost(map = "string, int32", tag = "4")]
    pub crypt: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(message, optional, tag = "5")]
    pub latency: ::core::option::Option<Latency>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Fields {
    Unspecified = 0,
    All = 1,
    Users = 2,
    Passwords = 3,
    Crypt = 4,
}
impl Fields {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FIELDS_UNSPECIFIED",
            Self::All => "FIELDS_ALL",
            Self::Users => "FIELDS_USERS",
            Self::Passwords => "FIELDS_PASSWORDS",
            Self::Crypt => "FIELDS_CRYPT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIELDS_UNSPECIFIED" => Some(Self::Unspecified),
            "FIELDS_ALL" => Some(Self::All),
            "FIELDS_USERS" => Some(Self::Users),
            "FIELDS_PASSWORDS" => Some(Self::Passwords),
            "FIELDS_CRYPT" => Some(Self::Crypt),
            _ => None,
        }
    }
}
include!("stats.v1.tonic.rs");
// @@protoc_insertion_point(module)