// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TodayRequest {
    #[prost(enumeration = "Fields", repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ByDateRequest {
    #[prost(enumeration = "Fields", repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "2")]
    pub day: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatValue {
    #[prost(map = "string, int64", tag = "1")]
    pub elements: ::std::collections::HashMap<::prost::alloc::string::String, i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatsResponse {
    #[prost(map = "string, message", tag = "1")]
    pub info: ::std::collections::HashMap<::prost::alloc::string::String, StatValue>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Fields {
    Unspecified = 0,
    All = 1,
    Users = 2,
    Passwords = 3,
    Crypt = 4,
}
impl Fields {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FIELDS_UNSPECIFIED",
            Self::All => "FIELDS_ALL",
            Self::Users => "FIELDS_USERS",
            Self::Passwords => "FIELDS_PASSWORDS",
            Self::Crypt => "FIELDS_CRYPT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIELDS_UNSPECIFIED" => Some(Self::Unspecified),
            "FIELDS_ALL" => Some(Self::All),
            "FIELDS_USERS" => Some(Self::Users),
            "FIELDS_PASSWORDS" => Some(Self::Passwords),
            "FIELDS_CRYPT" => Some(Self::Crypt),
            _ => None,
        }
    }
}
include!("stats.v1.tonic.rs");
// @@protoc_insertion_point(module)