// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/stats/v1/domain.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fields int32

const (
	Fields_FIELDS_UNSPECIFIED Fields = 0
	Fields_FIELDS_ALL         Fields = 1
	Fields_FIELDS_USERS       Fields = 2
	Fields_FIELDS_PASSWORDS   Fields = 3
	Fields_FIELDS_CRYPT       Fields = 4
)

// Enum value maps for Fields.
var (
	Fields_name = map[int32]string{
		0: "FIELDS_UNSPECIFIED",
		1: "FIELDS_ALL",
		2: "FIELDS_USERS",
		3: "FIELDS_PASSWORDS",
		4: "FIELDS_CRYPT",
	}
	Fields_value = map[string]int32{
		"FIELDS_UNSPECIFIED": 0,
		"FIELDS_ALL":         1,
		"FIELDS_USERS":       2,
		"FIELDS_PASSWORDS":   3,
		"FIELDS_CRYPT":       4,
	}
)

func (x Fields) Enum() *Fields {
	p := new(Fields)
	*p = x
	return p
}

func (x Fields) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fields) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Fields) Type() protoreflect.EnumType {
	return &file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes[0]
}

func (x Fields) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fields.Descriptor instead.
func (Fields) EnumDescriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{0}
}

type TodayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []Fields               `protobuf:"varint,1,rep,packed,name=fields,proto3,enum=stats.v1.Fields" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodayRequest) Reset() {
	*x = TodayRequest{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodayRequest) ProtoMessage() {}

func (x *TodayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodayRequest.ProtoReflect.Descriptor instead.
func (*TodayRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *TodayRequest) GetFields() []Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []Fields               `protobuf:"varint,1,rep,packed,name=fields,proto3,enum=stats.v1.Fields" json:"fields,omitempty"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByDateRequest) Reset() {
	*x = ByDateRequest{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByDateRequest) ProtoMessage() {}

func (x *ByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByDateRequest.ProtoReflect.Descriptor instead.
func (*ByDateRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *ByDateRequest) GetFields() []Fields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ByDateRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type StatValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      map[string]int64       `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatValue) Reset() {
	*x = StatValue{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatValue) ProtoMessage() {}

func (x *StatValue) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatValue.ProtoReflect.Descriptor instead.
func (*StatValue) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *StatValue) GetElements() map[string]int64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          map[string]*StatValue  `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetInfo() map[string]*StatValue {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_xyz_secureguard_v1_stats_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc = "" +
	"\n" +
	"(xyz/secureguard/v1/stats/v1/domain.proto\x12\bstats.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\fTodayRequest\x12(\n" +
	"\x06fields\x18\x01 \x03(\x0e2\x10.stats.v1.FieldsR\x06fields\"g\n" +
	"\rByDateRequest\x12(\n" +
	"\x06fields\x18\x01 \x03(\x0e2\x10.stats.v1.FieldsR\x06fields\x12,\n" +
	"\x03day\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"\x87\x01\n" +
	"\tStatValue\x12=\n" +
	"\belements\x18\x01 \x03(\v2!.stats.v1.StatValue.ElementsEntryR\belements\x1a;\n" +
	"\rElementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x94\x01\n" +
	"\rStatsResponse\x125\n" +
	"\x04info\x18\x01 \x03(\v2!.stats.v1.StatsResponse.InfoEntryR\x04info\x1aL\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.stats.v1.StatValueR\x05value:\x028\x01*j\n" +
	"\x06Fields\x12\x16\n" +
	"\x12FIELDS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FIELDS_ALL\x10\x01\x12\x10\n" +
	"\fFIELDS_USERS\x10\x02\x12\x14\n" +
	"\x10FIELDS_PASSWORDS\x10\x03\x12\x10\n" +
	"\fFIELDS_CRYPT\x10\x04BAZ?github.com/aesterial/secureguard/internal/api/v1/stats/v1;statsb\x06proto3"

var (
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = []any{
	(Fields)(0),                   // 0: stats.v1.Fields
	(*TodayRequest)(nil),          // 1: stats.v1.TodayRequest
	(*ByDateRequest)(nil),         // 2: stats.v1.ByDateRequest
	(*StatValue)(nil),             // 3: stats.v1.StatValue
	(*StatsResponse)(nil),         // 4: stats.v1.StatsResponse
	nil,                           // 5: stats.v1.StatValue.ElementsEntry
	nil,                           // 6: stats.v1.StatsResponse.InfoEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = []int32{
	0, // 0: stats.v1.TodayRequest.fields:type_name -> stats.v1.Fields
	0, // 1: stats.v1.ByDateRequest.fields:type_name -> stats.v1.Fields
	7, // 2: stats.v1.ByDateRequest.day:type_name -> google.protobuf.Timestamp
	5, // 3: stats.v1.StatValue.elements:type_name -> stats.v1.StatValue.ElementsEntry
	6, // 4: stats.v1.StatsResponse.info:type_name -> stats.v1.StatsResponse.InfoEntry
	3, // 5: stats.v1.StatsResponse.InfoEntry.value:type_name -> stats.v1.StatValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_stats_v1_domain_proto_init() }
func file_xyz_secureguard_v1_stats_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_stats_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_stats_v1_domain_proto = out.File
	file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = nil
}
