// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/stats/v1/domain.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fields int32

const (
	Fields_FIELDS_UNSPECIFIED Fields = 0
	Fields_FIELDS_ALL         Fields = 1
	Fields_FIELDS_USERS       Fields = 2
	Fields_FIELDS_PASSWORDS   Fields = 3
	Fields_FIELDS_CRYPT       Fields = 4
)

// Enum value maps for Fields.
var (
	Fields_name = map[int32]string{
		0: "FIELDS_UNSPECIFIED",
		1: "FIELDS_ALL",
		2: "FIELDS_USERS",
		3: "FIELDS_PASSWORDS",
		4: "FIELDS_CRYPT",
	}
	Fields_value = map[string]int32{
		"FIELDS_UNSPECIFIED": 0,
		"FIELDS_ALL":         1,
		"FIELDS_USERS":       2,
		"FIELDS_PASSWORDS":   3,
		"FIELDS_CRYPT":       4,
	}
)

func (x Fields) Enum() *Fields {
	p := new(Fields)
	*p = x
	return p
}

func (x Fields) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fields) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes[0].Descriptor()
}

func (Fields) Type() protoreflect.EnumType {
	return &file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes[0]
}

func (x Fields) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fields.Descriptor instead.
func (Fields) EnumDescriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{0}
}

type ByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByDateRequest) Reset() {
	*x = ByDateRequest{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByDateRequest) ProtoMessage() {}

func (x *ByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByDateRequest.ProtoReflect.Descriptor instead.
func (*ByDateRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *ByDateRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type TotalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Users          int32                  `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	Admins         int32                  `protobuf:"varint,2,opt,name=admins,proto3" json:"admins,omitempty"`
	Passwords      int32                  `protobuf:"varint,3,opt,name=passwords,proto3" json:"passwords,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TotalResponse) Reset() {
	*x = TotalResponse{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalResponse) ProtoMessage() {}

func (x *TotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalResponse.ProtoReflect.Descriptor instead.
func (*TotalResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *TotalResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *TotalResponse) GetAdmins() int32 {
	if x != nil {
		return x.Admins
	}
	return 0
}

func (x *TotalResponse) GetPasswords() int32 {
	if x != nil {
		return x.Passwords
	}
	return 0
}

func (x *TotalResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

type GraphPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPoint) Reset() {
	*x = GraphPoint{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPoint) ProtoMessage() {}

func (x *GraphPoint) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPoint.ProtoReflect.Descriptor instead.
func (*GraphPoint) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *GraphPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GraphPoint) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P50           float64                `protobuf:"fixed64,1,opt,name=p50,proto3" json:"p50,omitempty"`
	P90           float64                `protobuf:"fixed64,2,opt,name=p90,proto3" json:"p90,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *Latency) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *Latency) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopServices   map[string]int32       `protobuf:"bytes,1,rep,name=top_services,json=topServices,proto3" json:"top_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ActivityGraph []*GraphPoint          `protobuf:"bytes,3,rep,name=activity_graph,json=activityGraph,proto3" json:"activity_graph,omitempty"`
	RegisterGraph []*GraphPoint          `protobuf:"bytes,2,rep,name=register_graph,json=registerGraph,proto3" json:"register_graph,omitempty"`
	Crypt         map[string]int32       `protobuf:"bytes,4,rep,name=crypt,proto3" json:"crypt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Latency       *Latency               `protobuf:"bytes,5,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{4}
}

func (x *StatsResponse) GetTopServices() map[string]int32 {
	if x != nil {
		return x.TopServices
	}
	return nil
}

func (x *StatsResponse) GetActivityGraph() []*GraphPoint {
	if x != nil {
		return x.ActivityGraph
	}
	return nil
}

func (x *StatsResponse) GetRegisterGraph() []*GraphPoint {
	if x != nil {
		return x.RegisterGraph
	}
	return nil
}

func (x *StatsResponse) GetCrypt() map[string]int32 {
	if x != nil {
		return x.Crypt
	}
	return nil
}

func (x *StatsResponse) GetLatency() *Latency {
	if x != nil {
		return x.Latency
	}
	return nil
}

var File_xyz_secureguard_v1_stats_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc = "" +
	"\n" +
	"(xyz/secureguard/v1/stats/v1/domain.proto\x12\bstats.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\rByDateRequest\x12,\n" +
	"\x03day\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"\x84\x01\n" +
	"\rTotalResponse\x12\x14\n" +
	"\x05users\x18\x01 \x01(\x05R\x05users\x12\x16\n" +
	"\x06admins\x18\x02 \x01(\x05R\x06admins\x12\x1c\n" +
	"\tpasswords\x18\x03 \x01(\x05R\tpasswords\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\"R\n" +
	"\n" +
	"GraphPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"-\n" +
	"\aLatency\x12\x10\n" +
	"\x03p50\x18\x01 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\x02 \x01(\x01R\x03p90\"\xb7\x03\n" +
	"\rStatsResponse\x12K\n" +
	"\ftop_services\x18\x01 \x03(\v2(.stats.v1.StatsResponse.TopServicesEntryR\vtopServices\x12;\n" +
	"\x0eactivity_graph\x18\x03 \x03(\v2\x14.stats.v1.GraphPointR\ractivityGraph\x12;\n" +
	"\x0eregister_graph\x18\x02 \x03(\v2\x14.stats.v1.GraphPointR\rregisterGraph\x128\n" +
	"\x05crypt\x18\x04 \x03(\v2\".stats.v1.StatsResponse.CryptEntryR\x05crypt\x12+\n" +
	"\alatency\x18\x05 \x01(\v2\x11.stats.v1.LatencyR\alatency\x1a>\n" +
	"\x10TopServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"CryptEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*j\n" +
	"\x06Fields\x12\x16\n" +
	"\x12FIELDS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FIELDS_ALL\x10\x01\x12\x10\n" +
	"\fFIELDS_USERS\x10\x02\x12\x14\n" +
	"\x10FIELDS_PASSWORDS\x10\x03\x12\x10\n" +
	"\fFIELDS_CRYPT\x10\x04BAZ?github.com/aesterial/secureguard/internal/api/v1/stats/v1;statsb\x06proto3"

var (
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = []any{
	(Fields)(0),                   // 0: stats.v1.Fields
	(*ByDateRequest)(nil),         // 1: stats.v1.ByDateRequest
	(*TotalResponse)(nil),         // 2: stats.v1.TotalResponse
	(*GraphPoint)(nil),            // 3: stats.v1.GraphPoint
	(*Latency)(nil),               // 4: stats.v1.Latency
	(*StatsResponse)(nil),         // 5: stats.v1.StatsResponse
	nil,                           // 6: stats.v1.StatsResponse.TopServicesEntry
	nil,                           // 7: stats.v1.StatsResponse.CryptEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = []int32{
	8, // 0: stats.v1.ByDateRequest.day:type_name -> google.protobuf.Timestamp
	8, // 1: stats.v1.GraphPoint.time:type_name -> google.protobuf.Timestamp
	6, // 2: stats.v1.StatsResponse.top_services:type_name -> stats.v1.StatsResponse.TopServicesEntry
	3, // 3: stats.v1.StatsResponse.activity_graph:type_name -> stats.v1.GraphPoint
	3, // 4: stats.v1.StatsResponse.register_graph:type_name -> stats.v1.GraphPoint
	7, // 5: stats.v1.StatsResponse.crypt:type_name -> stats.v1.StatsResponse.CryptEntry
	4, // 6: stats.v1.StatsResponse.latency:type_name -> stats.v1.Latency
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_stats_v1_domain_proto_init() }
func file_xyz_secureguard_v1_stats_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_stats_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs,
		EnumInfos:         file_xyz_secureguard_v1_stats_v1_domain_proto_enumTypes,
		MessageInfos:      file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_stats_v1_domain_proto = out.File
	file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = nil
}
