// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/stats/v1/domain.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByDateRequest) Reset() {
	*x = ByDateRequest{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByDateRequest) ProtoMessage() {}

func (x *ByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByDateRequest.ProtoReflect.Descriptor instead.
func (*ByDateRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *ByDateRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type TotalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Users          int32                  `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	Admins         int32                  `protobuf:"varint,2,opt,name=admins,proto3" json:"admins,omitempty"`
	Passwords      int32                  `protobuf:"varint,3,opt,name=passwords,proto3" json:"passwords,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TotalResponse) Reset() {
	*x = TotalResponse{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalResponse) ProtoMessage() {}

func (x *TotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalResponse.ProtoReflect.Descriptor instead.
func (*TotalResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *TotalResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *TotalResponse) GetAdmins() int32 {
	if x != nil {
		return x.Admins
	}
	return 0
}

func (x *TotalResponse) GetPasswords() int32 {
	if x != nil {
		return x.Passwords
	}
	return 0
}

func (x *TotalResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

type GraphPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPoint) Reset() {
	*x = GraphPoint{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPoint) ProtoMessage() {}

func (x *GraphPoint) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPoint.ProtoReflect.Descriptor instead.
func (*GraphPoint) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *GraphPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GraphPoint) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P50           float64                `protobuf:"fixed64,1,opt,name=p50,proto3" json:"p50,omitempty"`
	P90           float64                `protobuf:"fixed64,2,opt,name=p90,proto3" json:"p90,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *Latency) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *Latency) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopServices   map[string]int32       `protobuf:"bytes,1,rep,name=top_services,json=topServices,proto3" json:"top_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UsersGraph    []*GraphPoint          `protobuf:"bytes,3,rep,name=users_graph,json=usersGraph,proto3" json:"users_graph,omitempty"`
	RegisterGraph []*GraphPoint          `protobuf:"bytes,2,rep,name=register_graph,json=registerGraph,proto3" json:"register_graph,omitempty"`
	CryptUses     map[string]int32       `protobuf:"bytes,4,rep,name=crypt_uses,json=cryptUses,proto3" json:"crypt_uses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ThemeUses     map[string]int32       `protobuf:"bytes,5,rep,name=theme_uses,json=themeUses,proto3" json:"theme_uses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LangUses      map[string]int32       `protobuf:"bytes,6,rep,name=lang_uses,json=langUses,proto3" json:"lang_uses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Latency       *Latency               `protobuf:"bytes,7,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{4}
}

func (x *Stats) GetTopServices() map[string]int32 {
	if x != nil {
		return x.TopServices
	}
	return nil
}

func (x *Stats) GetUsersGraph() []*GraphPoint {
	if x != nil {
		return x.UsersGraph
	}
	return nil
}

func (x *Stats) GetRegisterGraph() []*GraphPoint {
	if x != nil {
		return x.RegisterGraph
	}
	return nil
}

func (x *Stats) GetCryptUses() map[string]int32 {
	if x != nil {
		return x.CryptUses
	}
	return nil
}

func (x *Stats) GetThemeUses() map[string]int32 {
	if x != nil {
		return x.ThemeUses
	}
	return nil
}

func (x *Stats) GetLangUses() map[string]int32 {
	if x != nil {
		return x.LangUses
	}
	return nil
}

func (x *Stats) GetLatency() *Latency {
	if x != nil {
		return x.Latency
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_xyz_secureguard_v1_stats_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc = "" +
	"\n" +
	"(xyz/secureguard/v1/stats/v1/domain.proto\x12\x1bxyz.secureguard.v1.stats.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\rByDateRequest\x12,\n" +
	"\x03day\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"\x84\x01\n" +
	"\rTotalResponse\x12\x14\n" +
	"\x05users\x18\x01 \x01(\x05R\x05users\x12\x16\n" +
	"\x06admins\x18\x02 \x01(\x05R\x06admins\x12\x1c\n" +
	"\tpasswords\x18\x03 \x01(\x05R\tpasswords\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\"R\n" +
	"\n" +
	"GraphPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"-\n" +
	"\aLatency\x12\x10\n" +
	"\x03p50\x18\x01 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\x02 \x01(\x01R\x03p90\"\xa5\x06\n" +
	"\x05Stats\x12V\n" +
	"\ftop_services\x18\x01 \x03(\v23.xyz.secureguard.v1.stats.v1.Stats.TopServicesEntryR\vtopServices\x12H\n" +
	"\vusers_graph\x18\x03 \x03(\v2'.xyz.secureguard.v1.stats.v1.GraphPointR\n" +
	"usersGraph\x12N\n" +
	"\x0eregister_graph\x18\x02 \x03(\v2'.xyz.secureguard.v1.stats.v1.GraphPointR\rregisterGraph\x12P\n" +
	"\n" +
	"crypt_uses\x18\x04 \x03(\v21.xyz.secureguard.v1.stats.v1.Stats.CryptUsesEntryR\tcryptUses\x12P\n" +
	"\n" +
	"theme_uses\x18\x05 \x03(\v21.xyz.secureguard.v1.stats.v1.Stats.ThemeUsesEntryR\tthemeUses\x12M\n" +
	"\tlang_uses\x18\x06 \x03(\v20.xyz.secureguard.v1.stats.v1.Stats.LangUsesEntryR\blangUses\x12>\n" +
	"\alatency\x18\a \x01(\v2$.xyz.secureguard.v1.stats.v1.LatencyR\alatency\x1a>\n" +
	"\x10TopServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eCryptUsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eThemeUsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a;\n" +
	"\rLangUsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"I\n" +
	"\rStatsResponse\x128\n" +
	"\x05stats\x18\x01 \x01(\v2\".xyz.secureguard.v1.stats.v1.StatsR\x05statsBAZ?github.com/aesterial/secureguard/internal/api/v1/stats/v1;statsb\x06proto3"

var (
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_stats_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = []any{
	(*ByDateRequest)(nil),         // 0: xyz.secureguard.v1.stats.v1.ByDateRequest
	(*TotalResponse)(nil),         // 1: xyz.secureguard.v1.stats.v1.TotalResponse
	(*GraphPoint)(nil),            // 2: xyz.secureguard.v1.stats.v1.GraphPoint
	(*Latency)(nil),               // 3: xyz.secureguard.v1.stats.v1.Latency
	(*Stats)(nil),                 // 4: xyz.secureguard.v1.stats.v1.Stats
	(*StatsResponse)(nil),         // 5: xyz.secureguard.v1.stats.v1.StatsResponse
	nil,                           // 6: xyz.secureguard.v1.stats.v1.Stats.TopServicesEntry
	nil,                           // 7: xyz.secureguard.v1.stats.v1.Stats.CryptUsesEntry
	nil,                           // 8: xyz.secureguard.v1.stats.v1.Stats.ThemeUsesEntry
	nil,                           // 9: xyz.secureguard.v1.stats.v1.Stats.LangUsesEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = []int32{
	10, // 0: xyz.secureguard.v1.stats.v1.ByDateRequest.day:type_name -> google.protobuf.Timestamp
	10, // 1: xyz.secureguard.v1.stats.v1.GraphPoint.time:type_name -> google.protobuf.Timestamp
	6,  // 2: xyz.secureguard.v1.stats.v1.Stats.top_services:type_name -> xyz.secureguard.v1.stats.v1.Stats.TopServicesEntry
	2,  // 3: xyz.secureguard.v1.stats.v1.Stats.users_graph:type_name -> xyz.secureguard.v1.stats.v1.GraphPoint
	2,  // 4: xyz.secureguard.v1.stats.v1.Stats.register_graph:type_name -> xyz.secureguard.v1.stats.v1.GraphPoint
	7,  // 5: xyz.secureguard.v1.stats.v1.Stats.crypt_uses:type_name -> xyz.secureguard.v1.stats.v1.Stats.CryptUsesEntry
	8,  // 6: xyz.secureguard.v1.stats.v1.Stats.theme_uses:type_name -> xyz.secureguard.v1.stats.v1.Stats.ThemeUsesEntry
	9,  // 7: xyz.secureguard.v1.stats.v1.Stats.lang_uses:type_name -> xyz.secureguard.v1.stats.v1.Stats.LangUsesEntry
	3,  // 8: xyz.secureguard.v1.stats.v1.Stats.latency:type_name -> xyz.secureguard.v1.stats.v1.Latency
	4,  // 9: xyz.secureguard.v1.stats.v1.StatsResponse.stats:type_name -> xyz.secureguard.v1.stats.v1.Stats
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_stats_v1_domain_proto_init() }
func file_xyz_secureguard_v1_stats_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_stats_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_stats_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_stats_v1_domain_proto = out.File
	file_xyz_secureguard_v1_stats_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_stats_v1_domain_proto_depIdxs = nil
}
