// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/stats/v1/service.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_stats_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc = "" +
	"\n" +
	")xyz/secureguard/v1/stats/v1/service.proto\x12\bstats.v1\x1a(xyz/secureguard/v1/stats/v1/domain.proto2\x84\x01\n" +
	"\fStatsService\x128\n" +
	"\x05Today\x12\x16.stats.v1.TodayRequest\x1a\x17.stats.v1.StatsResponse\x12:\n" +
	"\x06ByDate\x12\x17.stats.v1.ByDateRequest\x1a\x17.stats.v1.StatsResponseBAZ?github.com/aesterial/secureguard/internal/api/v1/stats/v1;statsb\x06proto3"

var file_xyz_secureguard_v1_stats_v1_service_proto_goTypes = []any{
	(*TodayRequest)(nil),  // 0: stats.v1.TodayRequest
	(*ByDateRequest)(nil), // 1: stats.v1.ByDateRequest
	(*StatsResponse)(nil), // 2: stats.v1.StatsResponse
}
var file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs = []int32{
	0, // 0: stats.v1.StatsService.Today:input_type -> stats.v1.TodayRequest
	1, // 1: stats.v1.StatsService.ByDate:input_type -> stats.v1.ByDateRequest
	2, // 2: stats.v1.StatsService.Today:output_type -> stats.v1.StatsResponse
	2, // 3: stats.v1.StatsService.ByDate:output_type -> stats.v1.StatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_stats_v1_service_proto_init() }
func file_xyz_secureguard_v1_stats_v1_service_proto_init() {
	if File_xyz_secureguard_v1_stats_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_stats_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_stats_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_stats_v1_service_proto = out.File
	file_xyz_secureguard_v1_stats_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs = nil
}
