// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/stats/v1/service.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_stats_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc = "" +
	"\n" +
	")xyz/secureguard/v1/stats/v1/service.proto\x12\x1bxyz.secureguard.v1.stats.v1\x1a(xyz/secureguard/v1/stats/v1/domain.proto\x1a\x1bgoogle/protobuf/empty.proto2\x8a\x02\n" +
	"\fStatsService\x12K\n" +
	"\x05Today\x12\x16.google.protobuf.Empty\x1a*.xyz.secureguard.v1.stats.v1.StatsResponse\x12`\n" +
	"\x06ByDate\x12*.xyz.secureguard.v1.stats.v1.ByDateRequest\x1a*.xyz.secureguard.v1.stats.v1.StatsResponse\x12K\n" +
	"\x05Total\x12\x16.google.protobuf.Empty\x1a*.xyz.secureguard.v1.stats.v1.TotalResponseBAZ?github.com/aesterial/secureguard/internal/api/v1/stats/v1;statsb\x06proto3"

var file_xyz_secureguard_v1_stats_v1_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*ByDateRequest)(nil), // 1: xyz.secureguard.v1.stats.v1.ByDateRequest
	(*StatsResponse)(nil), // 2: xyz.secureguard.v1.stats.v1.StatsResponse
	(*TotalResponse)(nil), // 3: xyz.secureguard.v1.stats.v1.TotalResponse
}
var file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.v1.stats.v1.StatsService.Today:input_type -> google.protobuf.Empty
	1, // 1: xyz.secureguard.v1.stats.v1.StatsService.ByDate:input_type -> xyz.secureguard.v1.stats.v1.ByDateRequest
	0, // 2: xyz.secureguard.v1.stats.v1.StatsService.Total:input_type -> google.protobuf.Empty
	2, // 3: xyz.secureguard.v1.stats.v1.StatsService.Today:output_type -> xyz.secureguard.v1.stats.v1.StatsResponse
	2, // 4: xyz.secureguard.v1.stats.v1.StatsService.ByDate:output_type -> xyz.secureguard.v1.stats.v1.StatsResponse
	3, // 5: xyz.secureguard.v1.stats.v1.StatsService.Total:output_type -> xyz.secureguard.v1.stats.v1.TotalResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_stats_v1_service_proto_init() }
func file_xyz_secureguard_v1_stats_v1_service_proto_init() {
	if File_xyz_secureguard_v1_stats_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_stats_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_stats_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_stats_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_stats_v1_service_proto = out.File
	file_xyz_secureguard_v1_stats_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_stats_v1_service_proto_depIdxs = nil
}
