// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceInfo {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Password {
    #[prost(message, optional, tag = "1")]
    pub serv: ::core::option::Option<ServiceInfo>,
    #[prost(string, tag = "2")]
    pub login: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pass: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<Password>,
    #[prost(int32, tag = "2")]
    pub count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateRequest {
    #[prost(string, tag = "1")]
    pub service_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub login: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pass: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassDataResponse {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<Password>,
    #[prost(message, optional, tag = "2")]
    pub at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateRequest {
    #[prost(string, optional, tag = "1")]
    pub service_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub login: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub pass: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteResponse {
}
include!("xyz.secureguard.v1.passwords.v1.tonic.rs");
// @@protoc_insertion_point(module)