// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/sessions/v1/domain.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Revoke        *Session_RevokeInfo    `protobuf:"bytes,3,opt,name=revoke,proto3,oneof" json:"revoke,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3,oneof" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Session) GetRevoke() *Session_RevokeInfo {
	if x != nil {
		return x.Revoke
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type SessionsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Session             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsListResponse) Reset() {
	*x = SessionsListResponse{}
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsListResponse) ProtoMessage() {}

func (x *SessionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsListResponse.ProtoReflect.Descriptor instead.
func (*SessionsListResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *SessionsListResponse) GetList() []*Session {
	if x != nil {
		return x.List
	}
	return nil
}

type Session_RevokeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session_RevokeInfo) Reset() {
	*x = Session_RevokeInfo{}
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session_RevokeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session_RevokeInfo) ProtoMessage() {}

func (x *Session_RevokeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session_RevokeInfo.ProtoReflect.Descriptor instead.
func (*Session_RevokeInfo) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Session_RevokeInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *Session_RevokeInfo) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

var File_xyz_secureguard_v1_sessions_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDesc = "" +
	"\n" +
	"+xyz/secureguard/v1/sessions/v1/domain.proto\x12\x1exyz.secureguard.v1.sessions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12O\n" +
	"\x06revoke\x18\x03 \x01(\v22.xyz.secureguard.v1.sessions.v1.Session.RevokeInfoH\x00R\x06revoke\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\blastSeen\x88\x01\x01\x1aa\n" +
	"\n" +
	"RevokeInfo\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x129\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAtB\t\n" +
	"\a_revokeB\f\n" +
	"\n" +
	"_last_seen\"S\n" +
	"\x14SessionsListResponse\x12;\n" +
	"\x04list\x18\x01 \x03(\v2'.xyz.secureguard.v1.sessions.v1.SessionR\x04listB>Z<github.com/aesterial/secureguard/internal/api/v1/sessions/v1b\x06proto3"

var (
	file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xyz_secureguard_v1_sessions_v1_domain_proto_goTypes = []any{
	(*Session)(nil),               // 0: xyz.secureguard.v1.sessions.v1.Session
	(*SessionsListResponse)(nil),  // 1: xyz.secureguard.v1.sessions.v1.SessionsListResponse
	(*Session_RevokeInfo)(nil),    // 2: xyz.secureguard.v1.sessions.v1.Session.RevokeInfo
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_secureguard_v1_sessions_v1_domain_proto_depIdxs = []int32{
	2, // 0: xyz.secureguard.v1.sessions.v1.Session.revoke:type_name -> xyz.secureguard.v1.sessions.v1.Session.RevokeInfo
	3, // 1: xyz.secureguard.v1.sessions.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: xyz.secureguard.v1.sessions.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	3, // 3: xyz.secureguard.v1.sessions.v1.Session.last_seen:type_name -> google.protobuf.Timestamp
	0, // 4: xyz.secureguard.v1.sessions.v1.SessionsListResponse.list:type_name -> xyz.secureguard.v1.sessions.v1.Session
	3, // 5: xyz.secureguard.v1.sessions.v1.Session.RevokeInfo.revoked_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_sessions_v1_domain_proto_init() }
func file_xyz_secureguard_v1_sessions_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_sessions_v1_domain_proto != nil {
		return
	}
	file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_sessions_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_sessions_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_sessions_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_sessions_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_sessions_v1_domain_proto = out.File
	file_xyz_secureguard_v1_sessions_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_sessions_v1_domain_proto_depIdxs = nil
}
