// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/sessions/v1/service.proto

package v1

import (
	v1 "github.com/aesterial/secureguard/internal/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_sessions_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_sessions_v1_service_proto_rawDesc = "" +
	"\n" +
	",xyz/secureguard/v1/sessions/v1/service.proto\x12\x1exyz.secureguard.v1.sessions.v1\x1a+xyz/secureguard/v1/sessions/v1/domain.proto\x1a\x1exyz/secureguard/v1/types.proto\x1a\x1bgoogle/protobuf/empty.proto2\xca\x01\n" +
	"\x0fSessionsService\x12r\n" +
	"\aGetList\x121.xyz.secureguard.v1.RequestWithBooleanLimitOffset\x1a4.xyz.secureguard.v1.sessions.v1.SessionsListResponse\x12C\n" +
	"\x06Revoke\x12!.xyz.secureguard.v1.RequestWithID\x1a\x16.google.protobuf.EmptyB>Z<github.com/aesterial/secureguard/internal/api/v1/sessions/v1b\x06proto3"

var file_xyz_secureguard_v1_sessions_v1_service_proto_goTypes = []any{
	(*v1.RequestWithBooleanLimitOffset)(nil), // 0: xyz.secureguard.v1.RequestWithBooleanLimitOffset
	(*v1.RequestWithID)(nil),                 // 1: xyz.secureguard.v1.RequestWithID
	(*SessionsListResponse)(nil),             // 2: xyz.secureguard.v1.sessions.v1.SessionsListResponse
	(*emptypb.Empty)(nil),                    // 3: google.protobuf.Empty
}
var file_xyz_secureguard_v1_sessions_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.v1.sessions.v1.SessionsService.GetList:input_type -> xyz.secureguard.v1.RequestWithBooleanLimitOffset
	1, // 1: xyz.secureguard.v1.sessions.v1.SessionsService.Revoke:input_type -> xyz.secureguard.v1.RequestWithID
	2, // 2: xyz.secureguard.v1.sessions.v1.SessionsService.GetList:output_type -> xyz.secureguard.v1.sessions.v1.SessionsListResponse
	3, // 3: xyz.secureguard.v1.sessions.v1.SessionsService.Revoke:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_sessions_v1_service_proto_init() }
func file_xyz_secureguard_v1_sessions_v1_service_proto_init() {
	if File_xyz_secureguard_v1_sessions_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_sessions_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_sessions_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_sessions_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_sessions_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_sessions_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_sessions_v1_service_proto = out.File
	file_xyz_secureguard_v1_sessions_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_sessions_v1_service_proto_depIdxs = nil
}
