// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestWithID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithID) Reset() {
	*x = RequestWithID{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithID) ProtoMessage() {}

func (x *RequestWithID) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithID.ProtoReflect.Descriptor instead.
func (*RequestWithID) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RequestWithIdAndValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithIdAndValue) Reset() {
	*x = RequestWithIdAndValue{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithIdAndValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithIdAndValue) ProtoMessage() {}

func (x *RequestWithIdAndValue) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithIdAndValue.ProtoReflect.Descriptor instead.
func (*RequestWithIdAndValue) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *RequestWithIdAndValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestWithIdAndValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestWithValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithValue) Reset() {
	*x = RequestWithValue{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithValue) ProtoMessage() {}

func (x *RequestWithValue) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithValue.ProtoReflect.Descriptor instead.
func (*RequestWithValue) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *RequestWithValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestWithLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithLimit) Reset() {
	*x = RequestWithLimit{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithLimit) ProtoMessage() {}

func (x *RequestWithLimit) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithLimit.ProtoReflect.Descriptor instead.
func (*RequestWithLimit) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *RequestWithLimit) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RequestWithOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithOffset) Reset() {
	*x = RequestWithOffset{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithOffset) ProtoMessage() {}

func (x *RequestWithOffset) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithOffset.ProtoReflect.Descriptor instead.
func (*RequestWithOffset) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *RequestWithOffset) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RequestWithLimitAndOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithLimitAndOffset) Reset() {
	*x = RequestWithLimitAndOffset{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithLimitAndOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithLimitAndOffset) ProtoMessage() {}

func (x *RequestWithLimitAndOffset) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithLimitAndOffset.ProtoReflect.Descriptor instead.
func (*RequestWithLimitAndOffset) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *RequestWithLimitAndOffset) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RequestWithLimitAndOffset) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RequestWithBoolean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithBoolean) Reset() {
	*x = RequestWithBoolean{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithBoolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithBoolean) ProtoMessage() {}

func (x *RequestWithBoolean) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithBoolean.ProtoReflect.Descriptor instead.
func (*RequestWithBoolean) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *RequestWithBoolean) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type RequestWithBooleanLimitOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithBooleanLimitOffset) Reset() {
	*x = RequestWithBooleanLimitOffset{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithBooleanLimitOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithBooleanLimitOffset) ProtoMessage() {}

func (x *RequestWithBooleanLimitOffset) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithBooleanLimitOffset.ProtoReflect.Descriptor instead.
func (*RequestWithBooleanLimitOffset) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *RequestWithBooleanLimitOffset) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *RequestWithBooleanLimitOffset) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RequestWithBooleanLimitOffset) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Kdf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Iterations    int32                  `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	Parallelism   int32                  `protobuf:"varint,4,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kdf) Reset() {
	*x = Kdf{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kdf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kdf) ProtoMessage() {}

func (x *Kdf) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kdf.ProtoReflect.Descriptor instead.
func (*Kdf) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *Kdf) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Kdf) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Kdf) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *Kdf) GetParallelism() int32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

type RequestWithValueAndKdf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kdf           *Kdf                   `protobuf:"bytes,1,opt,name=kdf,proto3" json:"kdf,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Salt          string                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithValueAndKdf) Reset() {
	*x = RequestWithValueAndKdf{}
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithValueAndKdf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithValueAndKdf) ProtoMessage() {}

func (x *RequestWithValueAndKdf) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithValueAndKdf.ProtoReflect.Descriptor instead.
func (*RequestWithValueAndKdf) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *RequestWithValueAndKdf) GetKdf() *Kdf {
	if x != nil {
		return x.Kdf
	}
	return nil
}

func (x *RequestWithValueAndKdf) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RequestWithValueAndKdf) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

var File_xyz_secureguard_v1_types_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1exyz/secureguard/v1/types.proto\x12\x12xyz.secureguard.v1\"\x1f\n" +
	"\rRequestWithID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x15RequestWithIdAndValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x10RequestWithValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"(\n" +
	"\x10RequestWithLimit\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"+\n" +
	"\x11RequestWithOffset\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\"I\n" +
	"\x19RequestWithLimitAndOffset\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"*\n" +
	"\x12RequestWithBoolean\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"c\n" +
	"\x1dRequestWithBooleanLimitOffset\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"y\n" +
	"\x03Kdf\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\x05R\n" +
	"iterations\x12 \n" +
	"\vparallelism\x18\x04 \x01(\x05R\vparallelism\"m\n" +
	"\x16RequestWithValueAndKdf\x12)\n" +
	"\x03kdf\x18\x01 \x01(\v2\x17.xyz.secureguard.v1.KdfR\x03kdf\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\tR\x04saltB2Z0github.com/aesterial/secureguard/internal/api/v1b\x06proto3"

var (
	file_xyz_secureguard_v1_types_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_types_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_types_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_types_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_types_proto_rawDesc), len(file_xyz_secureguard_v1_types_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_types_proto_rawDescData
}

var file_xyz_secureguard_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_xyz_secureguard_v1_types_proto_goTypes = []any{
	(*RequestWithID)(nil),                 // 0: xyz.secureguard.v1.RequestWithID
	(*RequestWithIdAndValue)(nil),         // 1: xyz.secureguard.v1.RequestWithIdAndValue
	(*RequestWithValue)(nil),              // 2: xyz.secureguard.v1.RequestWithValue
	(*RequestWithLimit)(nil),              // 3: xyz.secureguard.v1.RequestWithLimit
	(*RequestWithOffset)(nil),             // 4: xyz.secureguard.v1.RequestWithOffset
	(*RequestWithLimitAndOffset)(nil),     // 5: xyz.secureguard.v1.RequestWithLimitAndOffset
	(*RequestWithBoolean)(nil),            // 6: xyz.secureguard.v1.RequestWithBoolean
	(*RequestWithBooleanLimitOffset)(nil), // 7: xyz.secureguard.v1.RequestWithBooleanLimitOffset
	(*Kdf)(nil),                           // 8: xyz.secureguard.v1.Kdf
	(*RequestWithValueAndKdf)(nil),        // 9: xyz.secureguard.v1.RequestWithValueAndKdf
}
var file_xyz_secureguard_v1_types_proto_depIdxs = []int32{
	8, // 0: xyz.secureguard.v1.RequestWithValueAndKdf.kdf:type_name -> xyz.secureguard.v1.Kdf
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_types_proto_init() }
func file_xyz_secureguard_v1_types_proto_init() {
	if File_xyz_secureguard_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_types_proto_rawDesc), len(file_xyz_secureguard_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_types_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_types_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_types_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_types_proto = out.File
	file_xyz_secureguard_v1_types_proto_goTypes = nil
	file_xyz_secureguard_v1_types_proto_depIdxs = nil
}
