// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithId {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithIdAndValue {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithValue {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithLimit {
    #[prost(int32, tag = "1")]
    pub limit: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithOffset {
    #[prost(int32, tag = "1")]
    pub offset: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithLimitAndOffset {
    #[prost(int32, tag = "1")]
    pub limit: i32,
    #[prost(int32, tag = "2")]
    pub offset: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithBoolean {
    #[prost(bool, tag = "1")]
    pub value: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithBooleanLimitOffset {
    #[prost(bool, tag = "1")]
    pub value: bool,
    #[prost(int32, tag = "2")]
    pub limit: i32,
    #[prost(int32, tag = "3")]
    pub offset: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Kdf {
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(int64, tag = "2")]
    pub memory: i64,
    #[prost(int32, tag = "3")]
    pub iterations: i32,
    #[prost(int32, tag = "4")]
    pub parallelism: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestWithValueAndKdf {
    #[prost(message, optional, tag = "1")]
    pub kdf: ::core::option::Option<Kdf>,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub salt: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
