// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/login/v1/domain.proto

package login

import (
	v1 "github.com/aesterial/secureguard/internal/api/v1"
	v11 "github.com/aesterial/secureguard/internal/api/v1/users/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MasterKey     string                 `protobuf:"bytes,3,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_login_v1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorizeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthorizeRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MasterKey     string                 `protobuf:"bytes,3,opt,name=master_key,json=masterKey,proto3" json:"master_key,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	KdfParams     *v1.Kdf                `protobuf:"bytes,5,opt,name=kdf_params,json=kdfParams,proto3" json:"kdf_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_login_v1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetMasterKey() string {
	if x != nil {
		return x.MasterKey
	}
	return ""
}

func (x *RegisterRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *RegisterRequest) GetKdfParams() *v1.Kdf {
	if x != nil {
		return x.KdfParams
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *v11.UserSelf          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_xyz_secureguard_v1_login_v1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetInfo() *v11.UserSelf {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *LoginResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

var File_xyz_secureguard_v1_login_v1_domain_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_login_v1_domain_proto_rawDesc = "" +
	"\n" +
	"(xyz/secureguard/v1/login/v1/domain.proto\x12\x1bxyz.secureguard.v1.login.v1\x1a(xyz/secureguard/v1/users/v1/domain.proto\x1a\x1exyz/secureguard/v1/types.proto\"i\n" +
	"\x10AuthorizeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"master_key\x18\x03 \x01(\tR\tmasterKey\"\xb4\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"master_key\x18\x03 \x01(\tR\tmasterKey\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\x126\n" +
	"\n" +
	"kdf_params\x18\x05 \x01(\v2\x17.xyz.secureguard.v1.KdfR\tkdfParams\"d\n" +
	"\rLoginResponse\x129\n" +
	"\x04info\x18\x01 \x01(\v2%.xyz.secureguard.v1.users.v1.UserSelfR\x04info\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asessionBAZ?github.com/aesterial/secureguard/internal/api/v1/login/v1;loginb\x06proto3"

var (
	file_xyz_secureguard_v1_login_v1_domain_proto_rawDescOnce sync.Once
	file_xyz_secureguard_v1_login_v1_domain_proto_rawDescData []byte
)

func file_xyz_secureguard_v1_login_v1_domain_proto_rawDescGZIP() []byte {
	file_xyz_secureguard_v1_login_v1_domain_proto_rawDescOnce.Do(func() {
		file_xyz_secureguard_v1_login_v1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_login_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_login_v1_domain_proto_rawDesc)))
	})
	return file_xyz_secureguard_v1_login_v1_domain_proto_rawDescData
}

var file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xyz_secureguard_v1_login_v1_domain_proto_goTypes = []any{
	(*AuthorizeRequest)(nil), // 0: xyz.secureguard.v1.login.v1.AuthorizeRequest
	(*RegisterRequest)(nil),  // 1: xyz.secureguard.v1.login.v1.RegisterRequest
	(*LoginResponse)(nil),    // 2: xyz.secureguard.v1.login.v1.LoginResponse
	(*v1.Kdf)(nil),           // 3: xyz.secureguard.v1.Kdf
	(*v11.UserSelf)(nil),     // 4: xyz.secureguard.v1.users.v1.UserSelf
}
var file_xyz_secureguard_v1_login_v1_domain_proto_depIdxs = []int32{
	3, // 0: xyz.secureguard.v1.login.v1.RegisterRequest.kdf_params:type_name -> xyz.secureguard.v1.Kdf
	4, // 1: xyz.secureguard.v1.login.v1.LoginResponse.info:type_name -> xyz.secureguard.v1.users.v1.UserSelf
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_login_v1_domain_proto_init() }
func file_xyz_secureguard_v1_login_v1_domain_proto_init() {
	if File_xyz_secureguard_v1_login_v1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_login_v1_domain_proto_rawDesc), len(file_xyz_secureguard_v1_login_v1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_secureguard_v1_login_v1_domain_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_login_v1_domain_proto_depIdxs,
		MessageInfos:      file_xyz_secureguard_v1_login_v1_domain_proto_msgTypes,
	}.Build()
	File_xyz_secureguard_v1_login_v1_domain_proto = out.File
	file_xyz_secureguard_v1_login_v1_domain_proto_goTypes = nil
	file_xyz_secureguard_v1_login_v1_domain_proto_depIdxs = nil
}
