// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/secureguard/v1/login/v1/service.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_secureguard_v1_login_v1_service_proto protoreflect.FileDescriptor

const file_xyz_secureguard_v1_login_v1_service_proto_rawDesc = "" +
	"\n" +
	")xyz/secureguard/v1/login/v1/service.proto\x12\x1bxyz.secureguard.v1.login.v1\x1a(xyz/secureguard/v1/login/v1/domain.proto2\xdc\x01\n" +
	"\fLoginService\x12d\n" +
	"\bRegister\x12,.xyz.secureguard.v1.login.v1.RegisterRequest\x1a*.xyz.secureguard.v1.login.v1.LoginResponse\x12f\n" +
	"\tAuthorize\x12-.xyz.secureguard.v1.login.v1.AuthorizeRequest\x1a*.xyz.secureguard.v1.login.v1.LoginResponseBAZ?github.com/aesterial/secureguard/internal/api/v1/login/v1;loginb\x06proto3"

var file_xyz_secureguard_v1_login_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: xyz.secureguard.v1.login.v1.RegisterRequest
	(*AuthorizeRequest)(nil), // 1: xyz.secureguard.v1.login.v1.AuthorizeRequest
	(*LoginResponse)(nil),    // 2: xyz.secureguard.v1.login.v1.LoginResponse
}
var file_xyz_secureguard_v1_login_v1_service_proto_depIdxs = []int32{
	0, // 0: xyz.secureguard.v1.login.v1.LoginService.Register:input_type -> xyz.secureguard.v1.login.v1.RegisterRequest
	1, // 1: xyz.secureguard.v1.login.v1.LoginService.Authorize:input_type -> xyz.secureguard.v1.login.v1.AuthorizeRequest
	2, // 2: xyz.secureguard.v1.login.v1.LoginService.Register:output_type -> xyz.secureguard.v1.login.v1.LoginResponse
	2, // 3: xyz.secureguard.v1.login.v1.LoginService.Authorize:output_type -> xyz.secureguard.v1.login.v1.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_secureguard_v1_login_v1_service_proto_init() }
func file_xyz_secureguard_v1_login_v1_service_proto_init() {
	if File_xyz_secureguard_v1_login_v1_service_proto != nil {
		return
	}
	file_xyz_secureguard_v1_login_v1_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_secureguard_v1_login_v1_service_proto_rawDesc), len(file_xyz_secureguard_v1_login_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_secureguard_v1_login_v1_service_proto_goTypes,
		DependencyIndexes: file_xyz_secureguard_v1_login_v1_service_proto_depIdxs,
	}.Build()
	File_xyz_secureguard_v1_login_v1_service_proto = out.File
	file_xyz_secureguard_v1_login_v1_service_proto_goTypes = nil
	file_xyz_secureguard_v1_login_v1_service_proto_depIdxs = nil
}
