// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Session {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub revoke: ::core::option::Option<session::RevokeInfo>,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
}
/// Nested message and enum types in `Session`.
pub mod session {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RevokeInfo {
        #[prost(bool, tag = "1")]
        pub revoked: bool,
        #[prost(message, optional, tag = "2")]
        pub revoked_at: ::core::option::Option<::prost_types::Timestamp>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionsListResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<Session>,
}
include!("xyz.secureguard.v1.sessions.v1.tonic.rs");
// @@protoc_insertion_point(module)